const DB_RECORRIDOS = {
"G800": {
        
    "recorridos": {

    "1873": [
        "1;ESTACION GUTIERREZ; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;RUSSELL; >IDA",
        "4;CRUZ DE PIEDRA; >IDA",
        "5;TRES ESQUINAS (ESC. CRUZ DE PIEDRA); >IDA",
        "6;LUNLUNTA; >VUELTA",
        "7;CRUZ DE PIEDRA; >VUELTA",
        "8;RUSSELL; >VUELTA",
        "9;MAIPU (PERON); >VUELTA",
        "10;ESTACION GUTIERREZ; >VUELTA"
    ],
    "801": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;CANCILLER (PEZZUTTI Y LEANEZ); >IDA",
        "4;LAT. E.CIVIT Y VIEYTES; >IDA",
        "5;PALMA Y OZAMIS; >IDA",
        "6;VIEYTES Y R60; >IDA",
        "7;CARBOMETAL; >VUELTA",
        "8;VIEYTES Y R60; >VUELTA",
        "9;PALMA Y OZAMIS; >VUELTA",
        "10;LAT. E.CIVIT Y VIEYTES; >VUELTA",
        "11;CANCILLER (PEZZUTTI Y LEANEZ); >VUELTA",
        "12;MAIPU (MUNICIPALIDAD); >VUELTA",
        "13;CONTROL MAIPU; >VUELTA"
    ],
    "802": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;ROTONDA BOMBEROS; >IDA",
        "4;VIEYTES Y BOEDO; >IDA",
        "5;EL CIRCUITO; >IDA",
        "6;BULNES Y SAN MARTIN; >VUELTA",
        "7;CARBOMETAL; >VUELTA",
        "8;VIEYTES Y BOEDO; >VUELTA",
        "9;ROTONDA BOMBEROS; >VUELTA",
        "10;MAIPU (MUNICIPALIDAD); >VUELTA",
        "11;CONTROL MAIPU; >VUELTA"
    ],
    "803": [
        "1;CONTROL MAIPU; >IDA",
        "2;OZAMIS Y 25 DE MAYO; >IDA",
        "3;VIEYTES Y V. CASTILLO; >IDA",
        "4;PASO Y ACCESO SUR; >IDA",
        "5;TERMINAL; >IDA",
        "6;CATAMARCA Y RIOJA; >VUELTA",
        "7;PASO Y ACCESO SUR; >VUELTA",
        "8;VIEYTES Y V. CASTILLO; >VUELTA",
        "9;OZAMIS Y 25 DE MAYO; >VUELTA",
        "10;CONTROL MAIPU; >VUELTA"
    ], // Se omitió: HTAL ITALIANO (DIFERENCIAL)
    "804": [
        "1;CONTROL MAIPU; >IDA",
        "2;OZAMIS Y 25 DE MAYO; >IDA",
        "3;VIEYTES Y V. CASTILLO; >IDA",
        "4;PASO Y TERRADA; >IDA",
        "5;RAWSON Y ACC.SUR; >IDA",
        "6;PTE OLIVE IDA; >IDA",
        "7;PZA GODOY CRUZ IDA; >IDA",
        "8;CATAMARCA Y RIOJA; >VUELTA",
        "9;PZA GODOY CRUZ (VUELTA); >VUELTA",
        "10;PTE OLIVE VUELTA; >VUELTA",
        "11;RAWSON Y ACC.SUR; >VUELTA",
        "12;PASO Y TERRADA; >VUELTA",
        "13;VIEYTES Y V. CASTILLO; >VUELTA",
        "14;OZAMIS Y 25 DE MAYO; >VUELTA",
        "15;CONTROL MAIPU; >VUELTA"
    ], // Se omitió: TERMINAL
    "810": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;URQUIZA Y ZANICHELLI; >IDA",
        "4;R. PEÑA Y URQUIZA; >IDA",
        "5;R. PEÑA Y GABRIELLI; >IDA",
        "6;PZA GODOY CRUZ IDA; >IDA",
        "7;TERMINAL; >IDA",
        "8;CATAMARCA Y RIOJA; >VUELTA",
        "9;LIBERTAD Y GODOY CRUZ; >VUELTA",
        "10;RODEO DE LA CRUZ; >VUELTA",
        "11;GOMEZ Y URQUIZA; >VUELTA",
        "12;OZAMIS Y CORREA; >VUELTA",
        "13;CONTROL MAIPU; >VUELTA"
    ],
    "811": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;URQUIZA Y ZANICHELLI; >IDA",
        "4;R. PEÑA Y URQUIZA; >IDA",
        "5;R. PEÑA Y GABRIELLI; >IDA",
        "6;PZA GODOY CRUZ IDA; >IDA",
        "7;TERMINAL; >IDA",
        "8;CATAMARCA Y RIOJA; >VUELTA",
        "9;LIBERTAD Y GODOY CRUZ; >VUELTA",
        "10;RODEO DE LA CRUZ; >VUELTA",
        "11;GOMEZ Y URQUIZA; >VUELTA",
        "12;URQUIZA Y ZANICHELLI; >VUELTA",
        "13;G.CRUZ Y BARCALA; >VUELTA",
        "14;CONTROL MAIPU; >VUELTA"
    ],
    "812": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;P. VAZQUEZ Y CORREA; >IDA",
        "4;R. PEÑA Y URQUIZA; >IDA",
        "5;KM 14; >IDA",
        "6;LIBERTAD Y GODOY CRUZ; >IDA",
        "7;MITRE Y G. CRUZ; >IDA",
        "8;CATAMARCA Y RIOJA; >VUELTA",
        "9;PZA GODOY CRUZ (VUELTA); >VUELTA",
        "10;R. PEÑA Y GABRIELLI; >VUELTA",
        "11;GOMEZ Y URQUIZA; >VUELTA",
        "12;URQUIZA Y ZANICHELLI; >VUELTA",
        "13;G.CRUZ Y BARCALA; >VUELTA",
        "14;CONTROL MAIPU; >VUELTA"
    ],
    "813": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;URQUIZA Y ZANICHELLI; >IDA",
        "4;R. PEÑA Y URQUIZA; >IDA",
        "5;KM 14; >IDA",
        "6;LIBERTAD Y GODOY CRUZ; >IDA",
        "7;MITRE Y G. CRUZ; >IDA",
        "8;CATAMARCA Y RIOJA; >VUELTA",
        "9;PZA GODOY CRUZ (VUELTA); >VUELTA",
        "10;R. PEÑA Y GABRIELLI; >VUELTA",
        "11;GOMEZ Y URQUIZA; >VUELTA",
        "12;URQUIZA Y ZANICHELLI; >VUELTA",
        "13;G.CRUZ Y BARCALA; >VUELTA",
        "14;CONTROL MAIPU; >VUELTA"
    ],
    "814": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;TROPERO Y NECOCHEA; >IDA",
        "4;ORTEGA; >IDA",
        "5;ESC. F. PELAEZ; >IDA",
        "6;ESC. F. PELAEZ; >VUELTA",
        "7;ORTEGA; >VUELTA",
        "8;TROPERO Y NECOCHEA; >VUELTA",
        "9;MAIPU (HOSPITAL); >VUELTA",
        "10;CONTROL MAIPU; >VUELTA"
    ],
    "815": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;URQUIZA Y ZANICHELLI; >IDA",
        "4;GOMEZ Y URQUIZA; >IDA",
        "5;R. PEÑA Y GABRIELLI; >IDA",
        "6;TERMINAL; >IDA",
        "7;CATAMARCA Y RIOJA; >VUELTA",
        "8;R. PEÑA Y GABRIELLI; >VUELTA",
        "9;GOMEZ Y URQUIZA; >VUELTA",
        "10;URQUIZA Y ZANICHELLI; >VUELTA",
        "11;CONTROL MAIPU; >VUELTA"
    ],
    "816": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;URQUIZA Y ZANICHELLI; >IDA",
        "4;GOMEZ Y URQUIZA; >IDA",
        "5;R. PEÑA Y URQUIZA; >IDA",
        "6;TERMINAL; >IDA",
        "7;CATAMARCA Y RIOJA; >VUELTA",
        "8;R. PEÑA Y URQUIZA; >VUELTA",
        "9;GOMEZ Y URQUIZA; >VUELTA",
        "10;URQUIZA Y ZANICHELLI; >VUELTA",
        "11;CONTROL MAIPU; >VUELTA"
    ],

    "817": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (MUNICIPALIDAD); >IDA",
        "3;MAITEN; >IDA",
        "4;BOEDO Y CORREA; >IDA",
        "5;GOMEZ Y URQUIZA; >IDA",
        "6;R. PEÑA Y URQUIZA; >IDA",
        "7;TERMINAL; >IDA",
        "8;CATAMARCA Y RIOJA; >VUELTA",
        "9;R. PEÑA Y URQUIZA; >VUELTA",
        "10;GOMEZ Y URQUIZA; >VUELTA",
        "11;BOEDO Y CORREA; >VUELTA",
        "12;MAITEN; >VUELTA",
        "13;CONTROL MAIPU; >VUELTA"
    ],
    "818": [
        "1;CONTROL-MAIPÚ; >IDA",
        "2;MAIPU (PERON); >VUELTA",
        "3;P. VAZQUEZ Y CORREA; >VUELTA",
        "4;CANAL PESCARA; >VUELTA",
        "5;R. PEÑA Y URQUIZA; >VUELTA",
        "6;V. VIÑEDO; >VUELTA",
        "7;Bº PICCIONE; >VUELTA",
        "8;V. VIÑEDO; >VUELTA",
        "9;CANAL PESCARA; >VUELTA",
        "10;OZAMIS Y CORREA; >VUELTA",
        "11;CONTROL-MAIPÚ; >VUELTA"
    ],
    "819": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;URQUIZA Y ZANICHELLI; >IDA",
        "4;ESC. F. PELAEZ; >VUELTA",
        "5;URQUIZA Y ZANICHELLI; >VUELTA",
        "6;MAIPU (HOSPITAL); >VUELTA",
        "7;CONTROL MAIPU; >VUELTA"
    ],
    "820": [
        "1;AMUPE (P. Moreno y Saavedra); >IDA",
        "2;B° T. SOSA; >IDA",
        "3;MAIPU (PERON); >IDA",
        "4;B° CANCILLER; >IDA",
        "5;MAZA Y J.B. JUSTO; >IDA",
        "6;MAZA Y SARMIENTO; >IDA",
        "7;VARIANTE Y SARMIENTO; >IDA",
        "8;PTE OLIVE IDA; >IDA",
        "9;PZA GODOY CRUZ IDA; >IDA",
        "10;TERMINAL; >IDA",
        "11;CATAMARCA Y RIOJA; >VUELTA",
        "12;PZA GODOY CRUZ (VUELTA); >VUELTA",
        "13;PTE OLIVE VUELTA; >VUELTA",
        "14;VARIANTE Y SARMIENTO; >VUELTA",
        "15;MAZA Y SARMIENTO; >VUELTA",
        "16;MAZA Y J.B. JUSTO; >VUELTA",
        "17;B° CANCILLER; >VUELTA",
        "18;MAIPU (MUNICIPALIDAD); >VUELTA",
        "19;B° T. SOSA; >VUELTA",
        "20;AMUPE (P. Moreno y Saavedra); >VUELTA"
    ],
    "821": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (MUNICIPALIDAD); >IDA",
        "3;MAZA Y SARMIENTO; >IDA",
        "4;SARMIENTO Y ACC. SUR; >IDA",
        // Se excluyó HTAL ITALIANO (DIFERENCIAL) por planilla NO
        "5;TERMINAL; >IDA",
        "6;CATAMARCA Y RIOJA; >VUELTA",
        "7;SARMIENTO Y ACC. SUR; >VUELTA",
        "8;MAZA Y SARMIENTO; >VUELTA",
        "9;OZAMIS Y 60 GRANADEROS; >VUELTA",
        "10;CONTROL MAIPU; >VUELTA"
    ],
    "860": [
        "1;ESTACION GUTIERREZ; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;RUSSELL; >IDA",
        "4;CRUZ DE PIEDRA; >IDA",
        "5;TRES ESQUINAS (V.ARANDA); >IDA",
        "6;LUNLUNTA; >VUELTA",
        "7;SAN GABRIEL - SAN ZENON (RECOARO); >VUELTA",
        "8;CRUZ DE PIEDRA; >VUELTA",
        "9;RUSSELL; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "10;MAIPU (PERON); >VUELTA",
        "11;ESTACION GUTIERREZ; >VUELTA"
    ],
    "861": [
        "1;ESTACION GUTIERREZ; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;RUSSELL; >IDA",
        "4;CRUZ DE PIEDRA; >IDA",
        "5;SAN GABRIEL - SAN ZENON (RECOARO); >IDA",
        "6;LUNLUNTA; >VUELTA",
        "7;TRES ESQUINAS (V.ARANDA); >VUELTA",
        "8;CRUZ DE PIEDRA; >VUELTA",
        "9;RUSSELL; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "10;MAIPU (PERON); >VUELTA",
        "11;ESTACION GUTIERREZ; >VUELTA"
    ],
    "863": [
        "1;Bº CICERONI; >IDA",
        "2;CRUZ DE PIEDRA; >IDA",
        "3;MAIPU (MUNICIPALIDAD); >IDA",
        "4;MAZA Y SARMIENTO; >IDA",
        "5;SARMIENTO Y ACC. SUR; >IDA",
        // Se excluyó HTAL ITALIANO (DIFERENCIAL) por planilla NO
        "6;TERMINAL; >VUELTA",
        "7;CATAMARCA Y RIOJA; >VUELTA",
        "8;SARMIENTO Y ACC. SUR; >VUELTA",
        "9;MAZA Y SARMIENTO; >VUELTA",
        "10;OZAMIS Y 60 GRANADEROS; >VUELTA",
        "11;CRUZ DE PIEDRA; >VUELTA",
        "12;Bº CICERONI; >VUELTA"
    ],
    "864": [
        "1;ESTACION GUTIERREZ; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;LA SUPERIORA; >IDA",
        "4;RUSSELL; >IDA",
        "5;TRES ESQUINAS (V.ARANDA); >IDA",
        "6;TRES ESQUINAS (V.ARANDA); >VUELTA",
        "7;RUSSELL; >VUELTA",
        "8;LA SUPERIORA; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "9;MAIPU (PERON); >VUELTA",
        "10;ESTACION GUTIERREZ; >VUELTA"
    ],
    "865": [
        "1;AMUPE (P. Y URQUIZA); >IDA",
        "2;TRES ESQUINAS (V.ARANDA); >IDA",
        "3;CRUZ DE PIEDRA (C.VIDELA Y OZAMIS); >IDA",
        "4;RUSSELL; >IDA",
        "5;LA SUPERIORA; >IDA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en IDA
        "6;MAIPU (PERON); >IDA",
        "7;VARIANTE (PTE HIERRO); >IDA",
        "8;VARIANTE Y SARMIENTO; >IDA",
        "9;ACCESO SUR Y R.PEÑA; >IDA",
        "10;TERMINAL; >VUELTA",
        "11;PEDRO MOLINA Y SAN MARTIN; >VUELTA",
        "12;ACCESO SUR Y R.PEÑA; >VUELTA",
        "13;VARIANTE Y SARMIENTO; >VUELTA",
        "14;VARIANTE (PTE HIERRO); >VUELTA",
        "15;MAIPU (HOSPITAL); >VUELTA",
        "16;Bº MALCAYAES; >VUELTA",
        "17;B° T. SOSA; >VUELTA",
        "18;AMUPE (P. Y URQUIZA); >VUELTA"
    ],
    "867": [
        "1;TRES ESQUINAS (ESC. CRUZ DE PIEDRA); >IDA",
        "2;CRUZ DE PIEDRA; >IDA",
        "3;MAIPU (MUNICIPALIDAD); >IDA",
        "4;MAZA Y SARMIENTO; >IDA",
        "5;SARMIENTO Y ACC. SUR; >IDA",
        // Se excluyó HTAL ITALIANO (DIFERENCIAL) por planilla NO
        "6;TERMINAL; >VUELTA",
        "7;CATAMARCA Y RIOJA; >VUELTA",
        "8;SARMIENTO Y ACC. SUR; >VUELTA",
        "9;MAZA Y SARMIENTO; >VUELTA",
        "10;OZAMIS Y 60 GRANADEROS; >VUELTA",
        "11;CRUZ DE PIEDRA; >VUELTA",
        "12;TRES ESQUINAS (ESC. CRUZ DE PIEDRA); >VUELTA"
    ],
    "870": [
        "1;CONTROL MAIPU; >IDA",
        "2;MAIPU (MUNICIPALIDAD); >IDA",
        // Se excluyó URQUIZA Y P.MORENO por planilla NO en IDA
        "3;TRES ESQUINAS (V.ARANDA); >IDA",
        "4;R14 Y CALLE NUEVA; >IDA",
        "5;LA CAPILLA Y SIMONOVICH; >IDA",
        "6;BRISAS DEL RIO; >IDA",
        "7;R14 Y SIMONOVICH; >IDA",
        "8;JUMEN; >IDA",
        "9;ESCUELA J. ESPADA; >VUELTA",
        "10;JUMEN; >VUELTA",
        "11;R14 Y SIMONOVICH; >VUELTA",
        "12;BRISAS DEL RIO; >VUELTA",
        "13;LA CAPILLA Y SIMONOVICH; >VUELTA",
        "14;R14 Y CALLE NUEVA; >VUELTA",
        "15;TRES ESQUINAS (V.ARANDA); >VUELTA",
        "16;TROPERO Y G.CRUZ; >VUELTA",
        "17;CONTROL MAIPU; >VUELTA"
    ],
    "871": [
        "1;ESTACION GUTIERREZ; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;RUSSELL; >IDA",
        "4;CRUZ DE PIEDRA; >IDA",
        "5;TRES ESQUINAS (V.ARANDA); >IDA",
        "6;R14 Y CALLE NUEVA; >IDA",
        "7;LA CAPILLA Y SIMONOVICH; >IDA",
        "8;R14 Y SIMONOVICH; >IDA",
        "9;JUMEN; >IDA",
        "10;ESCUELA J. ESPADA; >VUELTA",
        "11;JUMEN; >VUELTA",
        "12;R14 Y SIMONOVICH; >VUELTA",
        "13;LA CAPILLA Y SIMONOVICH; >VUELTA",
        "14;R14 Y CALLE NUEVA; >VUELTA",
        "15;TRES ESQUINAS (V.ARANDA); >VUELTA",
        "16;CRUZ DE PIEDRA; >VUELTA",
        "17;RUSSELL; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "18;MAIPU (PERON); >VUELTA",
        "19;ESTACION GUTIERREZ; >VUELTA"
    ],
    "872": [
        "1;ESTACION GUTIERREZ; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;LA SUPERIORA; >IDA",
        "4;RUSSELL; >IDA",
        "5;TRES ESQUINAS (V.ARANDA); >IDA",
        "6;R14 Y CALLE NUEVA; >IDA",
        "7;LA CAPILLA Y SIMONOVICH; >IDA",
        "8;R14 Y SIMONOVICH; >IDA",
        "9;JUMEN; >IDA",
        "10;ESCUELA J. ESPADA; >VUELTA",
        "11;JUMEN; >VUELTA",
        "12;R14 Y SIMONOVICH; >VUELTA",
        "13;LA CAPILLA Y SIMONOVICH; >VUELTA",
        "14;R14 Y CALLE NUEVA; >VUELTA",
        "15;TRES ESQUINAS (V.ARANDA); >VUELTA",
        "16;RUSSELL; >VUELTA",
        "17;LA SUPERIORA; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "18;MAIPU (PERON); >VUELTA",
        "19;ESTACION GUTIERREZ; >VUELTA"
    ],
    "880": [
        "1;ESTACION GUTIERREZ; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;RUSSELL; >IDA",
        "4;CRUZ DE PIEDRA; >IDA",
        "5;TRES ESQUINAS (V.ARANDA); >IDA",
        "6;CHACHINGO; >IDA",
        "7;PUEYRREDON Y U.VECINAL; >VUELTA",
        "8;CHACHINGO; >VUELTA",
        "9;TRES ESQUINAS (V.ARANDA); >VUELTA",
        "10;CRUZ DE PIEDRA; >VUELTA",
        "11;RUSSELL; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "12;MAIPU (PERON); >VUELTA",
        "13;ESTACION GUTIERREZ; >VUELTA"
    ],
    "881": [
        "1;ESTACION GUTIERREZ; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;LA SUPERIORA; >IDA",
        "4;RUSSELL; >IDA",
        "5;CRUZ DE PIEDRA; >IDA",
        "6;TRES ESQUINAS (V.ARANDA); >IDA",
        "7;CHACHINGO; >IDA",
        "8;PUEYRREDON Y U.VECINAL; >IDA",
        "9;CHACHINGO; >VUELTA",
        "10;TRES ESQUINAS (V.ARANDA); >VUELTA",
        "11;CRUZ DE PIEDRA; >VUELTA",
        "12;RUSSELL; >VUELTA",
        "13;LA SUPERIORA; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "14;MAIPU (PERON); >VUELTA",
        "15;ESTACION GUTIERREZ; >VUELTA"
    ],
    "896": [
        "1;AMUPE (P. Y URQUIZA); >IDA",
        "2;TRES ESQUINAS (V.ARANDA); >IDA",
        "3;CRUZ DE PIEDRA; >IDA",
        "4;TERRADA Y R60; >IDA",
        // Se excluyeron PASO Y ACCESO SUR y SARMIENTO Y ACC. SUR por planilla NO en IDA
        "5;TERMINAL; >IDA",
        "6;CATAMARCA Y RIOJA; >VUELTA",
        // Se excluyeron SARMIENTO Y ACC. SUR y PASO Y ACCESO SUR por planilla NO en VUELTA
        "7;TERRADA Y R60; >VUELTA",
        "8;CRUZ DE PIEDRA; >VUELTA",
        "9;TRES ESQUINAS (V.ARANDA); >VUELTA",
        "10;AMUPE (P. Y URQUIZA); >VUELTA"
    ],
    "897": [
        "1;ESTACION GUTIERREZ; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;RUSSELL; >IDA",
        "4;CRUZ DE PIEDRA; >IDA",
        "5;TRES ESQUINAS (V.ARANDA); >IDA",
        "6;R14 Y CALLE NUEVA; >IDA",
        "7;LA CAPILLA Y SIMONOVICH; >IDA",
        "8;R14 Y SIMONOVICH; >IDA",
        "9;JUMEN; >IDA",
        "10;ESCUELA J. ESPADA; >VUELTA",
        "11;JUMEN; >VUELTA",
        "12;R14 Y SIMONOVICH; >VUELTA",
        "13;LA CAPILLA Y SIMONOVICH; >VUELTA",
        "14;R14 Y CALLE NUEVA; >VUELTA",
        "15;TRES ESQUINAS (V.ARANDA); >VUELTA",
        "16;CRUZ DE PIEDRA; >VUELTA",
        "17;RUSSELL; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "18;MAIPU (PERON); >VUELTA",
        "19;ESTACION GUTIERREZ; >VUELTA"
    ],
    "898": [
        "1;ESTACION GUTIERREZ; >IDA",
        "2;MAIPU (PERON); >IDA",
        "3;RUSSELL; >IDA",
        "4;CRUZ DE PIEDRA; >IDA",
        "5;TRES ESQUINAS (V.ARANDA); >IDA",
        "6;R14 Y CALLE NUEVA; >IDA",
        "7;LA CAPILLA Y SIMONOVICH; >VUELTA",
        "8;R14 Y SIMONOVICH; >VUELTA",
        "9;JUMEN; >VUELTA",
        "10;ESCUELA J. ESPADA; >VUELTA",
        "11;JUMEN; >VUELTA",
        "12;R14 Y SIMONOVICH; >VUELTA",
        "13;BRISAS DEL RIO; >VUELTA",
        "14;LA CAPILLA Y SIMONOVICH; >VUELTA",
        "15;R14 Y CALLE NUEVA; >VUELTA",
        "16;TRES ESQUINAS (V.ARANDA); >VUELTA",
        "17;CRUZ DE PIEDRA; >VUELTA",
        "18;RUSSELL; >VUELTA",
        "19;MAIPU (MUNICIPALIDAD); >VUELTA",
        "20;MAIPU (PERON); >VUELTA",
        "21;ESTACION GUTIERREZ; >VUELTA"
    ]
}

},

"G200": {
        
        "recorridos": {
	    "1208": [
                "1;SALIDA TERMINAL; >IDA",
                "2;BELTRAN Y SAN MARTIN; >IDA",
                "3;25 DE MAYO Y LAS HERAS; >IDA",
                "4;INGRESO UNC; >IDA",
                "5;SALIDA UNC; >IDA",
                "6;Bº LA FAVORITA; >VUELTA",
                "7;SALIDA UNC; >VUELTA",
                "8;INGRESO UNC; >VUELTA",
                "9;B.SUR MER Y JUAN B. JUSTO; >VUELTA",
                "10;25 DE MAYO Y LAS HERAS; >VUELTA",
                "11;SAN MARTIN Y GODOY CRUZ; >VUELTA",
                "12;SALIDA TERMINAL; >VUELTA"
            ],
           
            "1293": [
                "1;SALIDA TERMINAL; >IDA",
                "2;ESC. EVA PERON; >VUELTA",
                "3;ROTONDA ORZALI; >VUELTA",
                "4;SALA 1º AUXILIOS; >VUELTA",
                "5;Bª LA FAVORITA; >VUELTA",
                "6;SALIDA TERMINAL; >VUELTA"
            ],
            "1297": [
                "1;SALIDA TERMINAL; >IDA",
                "2;ESC. VIDELA CORREA; >VUELTA",
                "3;B. SUR MER (LOCALES); >VUELTA",
                "4;Bº OLIVARES; >VUELTA",
                "5;Bª LA FAVORITA; >VUELTA",
                "6;SALIDA TERMINAL; >VUELTA"
            ],
            "200": [
                "1;CONTROL RODEO; >IDA",
                "2;ARCO; >IDA",
                "3;TIRASSO Y ACC; >IDA",
                "4;LIBERTAD; >IDA",
                "5;SARMIENTO; >IDA",
                "6;H.CENTRAL; >IDA",
                "7;BOULOGNE SUR MER; >IDA",
                "8;Bº LA FAVORITA; >VUELTA",
                "9;ROTONDA ORZALI; >VUELTA",
                "10;BOULOGNE SUR MER; >VUELTA",
                "11;PERU Y SARMIENTO; >VUELTA",
                "12;ALEM Y COSTANERA; >VUELTA",
                "13;SARMIENTO; >VUELTA",
                "14;LIBERTAD; >VUELTA",
                "15;TIRASSO Y ACC; >VUELTA",
                "16;ARCO; >VUELTA",
                "17;CONTROL RODEO; >VUELTA"
            ],
            "201": [
                "1;CONTROL RODEO; >IDA",
                "2;Bº ESCORIHUELA; >IDA",
                "3;TIRASSO Y ACC; >IDA",
                "4;LIBERTAD; >IDA",
                "5;SARMIENTO; >IDA",
                "6;H.CENTRAL; >IDA",
                "7;BOULOGNE SUR MER; >VUELTA",
                "8;Bª LA FAVORITA; >VUELTA",
                "9;ROTONDA ORZALI; >VUELTA",
                "10;BOULOGNE SUR MER; >VUELTA",
                "11;PERU Y SARMIENTO; >VUELTA",
                "12;ALEM Y COSTANERA; >VUELTA",
                "13;SARMIENTO; >VUELTA",
                "14;LIBERTAD; >VUELTA",
                "15;TIRASSO Y ACC; >VUELTA",
                "16;Bº ESCORIHUELA; >VUELTA",
                "17;CONTROL RODEO; >VUELTA"
            ],
            "202": [
                "1;CONTROL RODEO; >IDA",
                "2;ARCO; >IDA",
                "3;HUENTATA Y BERMEJO; >IDA",
                "4;TIRASSO Y LOS GUINDOS; >IDA",
                "5;URQUIZA Y ESPAÑA; >IDA",
                "6;P.CASTILLO Y AVELLANEDA; >IDA",
                "7;MITRE Y G. CRUZ; >IDA",
                "8;H.CENTRAL; >IDA",
                "9;MONTEVIDEO Y 25 DE MAYO; >VUELTA",
                "10;TERMINAL; >VUELTA",
                "11;MITRE Y G. CRUZ; >VUELTA",
                "12;P.CASTILLO Y AVELLANEDA; >VUELTA",
                "13;P.CASTILLO Y URQUIZA; >VUELTA",
                "14;TIRASSO Y LOS GUINDOS; >VUELTA",
                "15;HUENTATA Y BERMEJO; >VUELTA",
                "16;ARCO; >VUELTA",
                "17;CONTROL RODEO; >VUELTA"
            ],
            "203": [
                "1;CONTROL RODEO; >IDA",
                "2;ARCO; >IDA",
                "3;TIRASSO Y GODOY CRUZ; >IDA",
                "4;B° MUNICIPAL; >IDA",
                "5;B° SUYAI; >IDA",
                "6;TIRASSO Y GODOY CRUZ; >IDA",
                "7;SARMIENTO Y GODOY CRUZ; >IDA",
                "8;OBRIEN Y COSTANERA; >IDA",
                "9;MONTEVIDEO Y 25 DE MAYO; >VUELTA",
                "10;TERMINAL; >VUELTA",
                "11;SARMIENTO Y GODOY CRUZ; >VUELTA",
                "12;TIRASSO Y GODOY CRUZ; >VUELTA",
                "13;B° SUYAI; >VUELTA",
                "14;B° MUNICIPAL; >VUELTA",
                "15;TIRASSO Y GODOY CRUZ; >VUELTA",
                "16;ARCO; >VUELTA",
                "17;CONTROL RODEO; >VUELTA"
            ],
            "204": [
                "1;CONTROL RODEO; >IDA",
                "2;Bº ESCORIHUELA; >IDA",
                "3;TIRASSO Y ACC; >IDA",
                "4;TIRASSO Y TOMAS DE AQUINO; >IDA",
                "5;B° PRADERAS DEL SOL; >IDA",
                "6;B° PARAGUAY; >IDA",
                "7;TIRASSO Y GODOY CRUZ; >IDA",
                "8;SARMIENTO Y GODOY CRUZ; >IDA",
                "9;OBRIEN Y COSTANERA; >IDA",
                "10;MONTEVIDEO Y 25 DE MAYO; >VUELTA",
                "11;TERMINAL; >VUELTA",
                "12;SARMIENTO Y GODOY CRUZ; >VUELTA",
                "13;TIRASSO Y GODOY CRUZ; >VUELTA",
                "14;B° PRADERAS DEL SOL; >VUELTA",
                "15;Bº ESCORIHUELA; >VUELTA",
                "16;CONTROL RODEO; >VUELTA"
            ],
            "205": [
                "1;SALIDA TERMINAL; >IDA",
                "2;BELTRAN Y SAN MARTIN; >IDA",
                "3;25 DE MAYO Y LAS HERAS; >IDA",
                "4;INGRESO UNC; >IDA",
                "5;Bº LA FAVORITA; >VUELTA",
                "6;INGRESO UNC; >VUELTA",
                "7;B.SUR MER Y JUAN B. JUSTO; >VUELTA",
                "8;25 DE MAYO Y LAS HERAS; >VUELTA",
                "9;SAN MARTIN Y GODOY CRUZ; >VUELTA",
                "10;SALIDA TERMINAL; >VUELTA"
            ],
            "206": [
                "1;SALIDA TERMINAL; >IDA",
                "2;H.CENTRAL; >IDA",
                "3;PATRICIAS Y MONTEVIDEO; >IDA",
                "4;SARMIENTO Y PERU; >IDA",
                "5;B. SUR MER (LOCALES); >IDA",
                "6;ROTONDA ORZALI.; >IDA",
                "7;Bª LA FAVORITA; >IDA",
                "8;ESC. CLARET; >IDA",
                "9;LOS PUESTOS; >VUELTA",
                "10;ESC. CLARET; >VUELTA",
                "11;B. SUR MER (LOCALES); >VUELTA",
                "12;SARMIENTO Y 25 DE MAYO; >VUELTA",
                "13;PEDRO MOLINA Y SAN MARTIN; >VUELTA",
                "14;H.CENTRAL; >VUELTA",
                "15;SALIDA TERMINAL; >VUELTA"
            ],
            "207": [
                "1;SALIDA TERMINAL; >IDA",
                "2;MONTEVIDEO Y CHILE; >IDA",
                "3;B. SUR MER (LOCALES); >IDA",
                "4;CLUB REGATTAS; >IDA",
                "5;ROTONDA ORZALI; >IDA",
                "6;HOSPITAL LAGOMAGGIORE; >IDA",
                "7;USPALLATA Y PADRE LLORENS; >IDA",
                "8;ROTONDA ORZALI.; >IDA",
                "9;Bº LA FAVORITA; >VUELTA",
                "10;HOSPITAL LAGOMAGGIORE; >VUELTA",
                "11;CLUB REGATTAS; >VUELTA",
                "12;B. SUR MER (LOCALES); >VUELTA",
                "13;PATRICIAS Y MONTEVIDEO; >VUELTA",
                "14;PEDRO MOLINA Y SAN MARTIN; >VUELTA",
                "15;H.CENTRAL; >VUELTA",
                "16;SALIDA TERMINAL; >VUELTA"
            ],
            "208": [
                "1;SALIDA TERMINAL; >IDA",
                "2;BELTRAN Y SAN MARTIN; >IDA",
                "3;25 DE MAYO Y LAS HERAS; >IDA",
                "4;INGRESO UNC; >IDA",
                "5;SALIDA UNC; >IDA",
                "6;Bº LA FAVORITA; >IDA",
                "7;SALIDA UNC; >VUELTA",
                "8;INGRESO UNC; >VUELTA",
                "9;B.SUR MER Y JUAN B. JUSTO; >VUELTA",
                "10;25 DE MAYO Y LAS HERAS; >VUELTA",
                "11;SAN MARTIN Y GODOY CRUZ; >VUELTA",
                "12;SALIDA TERMINAL; >VUELTA"
            ],
            "221": [
                "1;SALIDA TERMINAL; >IDA",
                "2;COLON Y PATRICIAS; >IDA",
                "3;RIOJA Y RONDEAU; >IDA",
                "4;SARMIENTO Y ACCESO ESTE; >IDA",
                "5;ARENALES Y ACCESO ESTE; >IDA",
                "6;TAPON MOYANO; >IDA",
                "7;PONCE Y BANDERA; >IDA",
                "8;DURAND; >IDA",
                "9;PUENTE DE HIERRO; >IDA",
                "10;VIOLETAS; >IDA",
                "11;EL VERGEL; >IDA",
                "12;VIOLETAS; >VUELTA",
                "13;PUENTE DE HIERRO; >VUELTA",
                "14;DURAND; >VUELTA",
                "15;PONCE Y BANDERA; >VUELTA",
                "16;TAPON MOYANO; >VUELTA",
                "17;ARENALES Y ACCESO ESTE; >VUELTA",
                "18;SARMIENTO Y ACCESO ESTE; >VUELTA",
                "19;COLON Y PATRICIAS; >VUELTA",
                "20;RIOJA Y RONDEAU; >VUELTA",
                "21;SALIDA TERMINAL; >VUELTA"
            ],
            "230": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;DURAND; >IDA",
                "3;MILAGROS Y GODOY CRUZ; >IDA",
                "4;ARCO; >IDA",
                "5;TIRASSO Y ACC; >IDA",
                "6;ARENALES; >IDA",
                "7;SARMIENTO Y ACCESO ESTE; >IDA",
                "8;H.CENTRAL; >IDA",
                "9;COLON Y PATRICIAS; >VUELTA",
                "10;RIOJA Y RONDEAU; >VUELTA",
                "11;SARMIENTO Y ACCESO ESTE; >VUELTA",
                "12;ARENALES; >VUELTA",
                "13;TIRASSO Y ACC; >VUELTA",
                "14;ARCO; >VUELTA",
                "15;MILAGROS Y GODOY CRUZ; >VUELTA",
                "16;DURAND; >VUELTA",
                "17;CONTROL CORRALITOS; >VUELTA"
            ],
            "232": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;SEVERO Y R20; >IDA",
                "3;MILAGROS Y GODOY CRUZ; >IDA",
                "4;GODOY CRUZ Y BUENOS VECINOS; >IDA",
                "5;ARCO; >IDA",
                "6;TIRASSO Y ACC; >IDA",
                "7;ESPAÑA Y LIBERTAD; >VUELTA",
                "8;ARENALES Y BANDERA; >VUELTA",
                "9;TIRASSO Y ACC; >VUELTA",
                "10;ARCO; >VUELTA",
                "11;GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "12;SEVERO Y R20; >VUELTA",
                "13;CONTROL CORRALITOS; >VUELTA"
            ],
            "233": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;DURAND; >IDA",
                "3;GODOY CRUZ Y BUENOS VECINOS; >IDA",
                "4;ARCO; >IDA",
                "5;TIRASSO Y ACC; >IDA",
                "6;ARENALES; >IDA",
                "7;SARMIENTO; >IDA",
                "8;H.CENTRAL; >VUELTA",
                "9;TERMINAL; >VUELTA",
                "10;SARMIENTO; >VUELTA",
                "11;ARENALES; >VUELTA",
                "12;TIRASSO Y ACC; >VUELTA",
                "13;ARCO; >VUELTA",
                "14;GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "15;DURAND; >VUELTA",
                "16;CONTROL CORRALITOS; >VUELTA"
            ],
            "234": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;SAN JUAN Y SEVERO C.; >IDA",
                "3;GODOY CRUZ Y BUENOS VECINOS; >IDA",
                "4;ARCO; >IDA",
                "5;TIRASSO Y GODOY CRUZ; >IDA",
                "6;ARENALES Y G.CRUZ; >IDA",
                "7;SARMIENTO Y GODOY CRUZ; >IDA",
                "8;H.CENTRAL; >IDA",
                "9;TERMINAL; >VUELTA",
                "10;SARMIENTO Y GODOY CRUZ; >VUELTA",
                "11;ARENALES Y G.CRUZ; >VUELTA",
                "12;TIRASSO Y GODOY CRUZ; >VUELTA",
                "13;ARCO; >VUELTA",
                "14;GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "15;SAN JUAN Y SEVERO C.; >VUELTA",
                "16;CONTROL CORRALITOS; >VUELTA"
            ],
            "235": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;SEVERO Y FERRARI; >IDA",
                "3;FERRARI Y BUENOS VECINOS; >IDA",
                "4;ESC. LUGONES; >IDA",
                "5;GODOY CRUZ Y BUENOS VECINOS; >IDA",
                "6;ARCO; >IDA",
                "7;TIRASSO Y GODOY CRUZ; >IDA",
                "8;ARENALES Y G.CRUZ; >IDA",
                "9;SARMIENTO Y GODOY CRUZ; >IDA",
                "10;H.CENTRAL; >IDA",
                "11;RIOJA Y RONDEAU; >IDA",
                "12;TERMINAL; >VUELTA",
                "13;SARMIENTO Y GODOY CRUZ; >VUELTA",
                "14;ARENALES Y G.CRUZ; >VUELTA",
                "15;TIRASSO Y GODOY CRUZ; >VUELTA",
                "16;ARCO; >VUELTA",
                "17;GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "18;ESC. LUGONES; >VUELTA",
                "19;FERRARI Y BUENOS VECINOS; >VUELTA",
                "20;SEVERO Y FERRARI; >VUELTA",
                "21;CONTROL CORRALITOS; >VUELTA"
            ],
            "236": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;SEVERO Y FERRARI; >VUELTA",
                "3;FERRARI Y BUENOS VECINOS; >VUELTA",
                "4;SANCHEZ Y BUENOS AIRES; >VUELTA",
                "5;ESC. LUGONES; >VUELTA",
                "6;GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "7;KM 14; >VUELTA",
                "8;PONCE Y BANDERA; >VUELTA",
                "9;ARCO DE RODEO; >VUELTA",
                "10;KM 14; >VUELTA",
                "11;GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "12;ESC. LUGONES; >VUELTA",
                "13;SANCHEZ Y BUENOS AIRES; >VUELTA",
                "14;FERRARI Y BUENOS VECINOS; >VUELTA",
                "15;SEVERO Y FERRARI; >VUELTA",
                "16;CONTROL CORRALITOS; >VUELTA"
            ],
            "240": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;DURAND; >VUELTA",
                "3;R20 Y RECONQUISTA; >VUELTA",
                "4;V.HUGO Y H.PRIMO; >VUELTA",
                "5;PRIMAVERA; >VUELTA",
                "6;ARCO; >VUELTA",
                "7;TIRASSO Y GODOY CRUZ; >VUELTA",
                "8;URQUIZA Y G.CRUZ; >VUELTA",
                "9;BANDERA Y LIBERTAD; >VUELTA",
                "10;BANDERA Y BOLIVIA; >VUELTA",
                "11;SARMIENTO; >VUELTA",
                "12;ARENALES; >VUELTA",
                "13;MUNICIPALIDAD; >VUELTA",
                "14;URQUIZA Y G.CRUZ; >VUELTA",
                "15;TIRASSO Y GODOY CRUZ; >VUELTA",
                "16;ARCO; >VUELTA",
                "17;PRIMAVERA; >VUELTA",
                "18;V.HUGO Y H.PRIMO; >VUELTA",
                "19;R20 Y RECONQUISTA; >VUELTA",
                "20;DURAND; >VUELTA",
                "21;CONTROL CORRALITOS; >VUELTA"
            ],
            "241": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;DURAND; >IDA",
                "3;R20 Y SERPA; >IDA",
                "4;PRIMAVERA; >IDA",
                "5;DIABLILLO Y ARGUMEDO; >IDA",
                "6;ROTONDA SALCEDO; >IDA",
                "7;MILAGROS Y GODOY CRUZ; >IDA",
                "8;ARCO; >IDA",
                "9;TIRASSO Y GODOY CRUZ; >IDA",
                "10;SARMIENTO Y GODOY CRUZ; >IDA",
                "11;H.CENTRAL; >VUELTA",
                "12;TERMINAL; >VUELTA",
                "13;SARMIENTO Y GODOY CRUZ; >VUELTA",
                "14;TIRASSO Y GODOY CRUZ; >VUELTA",
                "15;ARCO; >VUELTA",
                "16;MILAGROS Y GODOY CRUZ; >VUELTA",
                "17;ROTONDA SALCEDO; >VUELTA",
                "18;PRIMAVERA; >VUELTA",
                "19;R20 Y SERPA; >VUELTA",
                "20;DURAND; >VUELTA",
                "21;CONTROL CORRALITOS; >VUELTA"
            ],
            "242": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;DURAND; >IDA",
                "3;BUENOS AIRES Y SAAVEDRA; >IDA",
                "4;R20 Y SERPA; >IDA",
                "5;PRIMAVERA; >IDA",
                "6;DIABLILLO Y PALADINI; >IDA",
                "7;SEVERO Y ARGUMEDO; >IDA",
                "8;MILAGROS Y BANDERA; >IDA",
                "9;ARCO; >IDA",
                "10;TIRASSO Y GODOY CRUZ; >IDA",
                "11;SARMIENTO Y GODOY CRUZ; >IDA",
                "12;H.CENTRAL; >IDA",
                "13;TERMINAL; >VUELTA",
                "14;SARMIENTO Y GODOY CRUZ; >VUELTA",
                "15;TIRASSO Y GODOY CRUZ; >VUELTA",
                "16;ARCO; >VUELTA",
                "17;MILAGROS Y BANDERA; >VUELTA",
                "18;SEVERO Y ARGUMEDO; >VUELTA",
                "19;PRIMAVERA; >VUELTA",
                "20;R20 Y SERPA; >VUELTA",
                "21;BUENOS AIRES Y SAAVEDRA; >VUELTA",
                "22;DURAND; >VUELTA"
            ],
            "250": [
                "1;CONTROL RODEO; >IDA",
                "2;PASCUAL LAURIENTE; >IDA",
                "3;SEVERO Y R20; >IDA",
                "4;2 DE MAYO; >IDA",
                "5;SERPA Y MITRE; >IDA",
                "6;R20 Y LOS ALAMOS; >IDA",
                "7;ROMA Y DON BOSCO; >VUELTA",
                "8;ROMA Y SAN JOSE; >VUELTA",
                "9;LOS BAÑOS Y LAT. ACCCESO ESTE; >VUELTA",
                "10;HTAL. METRAUX; >VUELTA",
                "11;R50 Y LOS BAÑOS; >VUELTA",
                "12;PASCUAL LAURIENTE; >VUELTA",
                "13;CONTROL RODEO; >VUELTA"
            ],
            "251": [
                "1;CONTROL RODEO; >IDA",
                "2;PASCUAL LAURIENTE; >IDA",
                "3;R50 Y LOS BAÑOS; >IDA",
                "4;HTAL. METRAUX; >IDA",
                "5;LOS BAÑOS Y LAT. ACCCESO ESTE; >IDA",
                "6;ROMA Y SAN JOSE; >IDA",
                "7;ROMA Y DON BOSCO; >VUELTA",
                "8;R20 Y LOS ALAMOS; >VUELTA",
                "9;SERPA Y MITRE; >VUELTA",
                "10;2 DE MAYO; >VUELTA",
                "11;SEVERO Y R20; >VUELTA",
                "12;PASCUAL LAURIENTE; >VUELTA",
                "13;CONTROL RODEO; >VUELTA"
            ],
            "252": [
                "1;SALIDA TERMINAL; >IDA",
                "2;SALTA Y GARIBALDI; >IDA",
                "3;SARMIENTO; >IDA",
                "4;LIBERTAD; >IDA",
                "5;URQUIZA; >IDA",
                "6;TIRASSO Y ACC; >IDA",
                "7;ARCO; >IDA",
                "8;KM 8; >IDA",
                "9;R50 Y DON BOSCO; >IDA",
                "10;R20 Y DON BOSCO; >VUELTA",
                "11;R50 Y DON BOSCO; >VUELTA",
                "12;KM 8; >VUELTA",
                "13;ARCO; >VUELTA",
                "14;TIRASSO Y ACC; >VUELTA",
                "15;URQUIZA; >VUELTA",
                "16;LIBERTAD; >VUELTA",
                "17;SARMIENTO; >VUELTA",
                "18;H.CENTRAL; >VUELTA",
                "19;SALIDA TERMINAL; >VUELTA"
            ],
            "260": [
                "1;SALIDA TERMINAL; >IDA",
                "2;CATAMARCA Y RIOJA; >IDA",
                "3;SARMIENTO Y ACCESO ESTE; >IDA",
                "4;ARENALES Y ACCESO ESTE; >IDA",
                "5;TIRASSO Y ACC; >IDA",
                "6;ARCO; >IDA",
                "7;KM 11; >IDA",
                "8;PRIMAVERA; >IDA",
                "9;Bº 25 DE MAYO; >IDA",
                "10;R50 Y DON BOSCO; >IDA",
                "11;HTAL. METRAUX; >VUELTA",
                "12;R50 Y LOS BAÑOS; >VUELTA",
                "13;R50 Y SERPA; >VUELTA",
                "14;R20 Y SERPA; >VUELTA",
                "15;PRIMAVERA; >VUELTA",
                "16;KM 8; >VUELTA",
                "17;ARCO; >VUELTA",
                "18;TIRASSO Y ACC; >VUELTA",
                "19;ARENALES Y ACCESO ESTE; >VUELTA",
                "20;SARMIENTO Y ACCESO ESTE; >VUELTA",
                "21;H.CENTRAL; >VUELTA",
                "22;SALIDA TERMINAL; >VUELTA"
            ],
            "261": [
                "1;SALIDA TERMINAL; >IDA",
                "2;CATAMARCA Y RIOJA; >IDA",
                "3;SARMIENTO Y ACCESO ESTE; >IDA",
                "4;ARENALES Y ACCESO ESTE; >IDA",
                "5;TIRASSO Y ACC; >IDA",
                "6;ARCO; >IDA",
                "7;KM 11; >IDA",
                "8;R50 Y DON BOSCO; >IDA",
                "9;R20 Y DON BOSCO; >VUELTA",
                "10;ROMA Y DON BOSCO; >VUELTA",
                "11;ROMA Y SAN JOSE; >VUELTA",
                "12;R50 Y LOS BAÑOS; >VUELTA",
                "13;KM 11; >VUELTA",
                "14;ARCO; >VUELTA",
                "15;TIRASSO Y ACC; >VUELTA",
                "16;ARENALES Y ACCESO ESTE; >VUELTA",
                "17;SARMIENTO Y ACCESO ESTE; >VUELTA",
                "18;H.CENTRAL; >VUELTA",
                "19;SALIDA TERMINAL; >VUELTA"
            ],
            "270": [
                "1;CONTROL RODEO; >IDA",
                "2;PASCUAL LAURIENTE; >IDA",
                "3;R50 Y LOS ALAMOS; >IDA",
                "4;R20 Y LOS ALAMOS; >IDA",
                "5;R20 Y R33; >IDA",
                "6;ESCUELA TITARELLI; >VUELTA",
                "7;R50 Y LAS MARGARITAS; >VUELTA",
                "8;R50 Y LOS BAÑOS; >VUELTA",
                "9;KM 8; >VUELTA",
                "10;PASCUAL LAURIENTE; >VUELTA",
                "11;CONTROL RODEO; >VUELTA"
            ],
            "271": [
                "1;CONTROL RODEO; >IDA",
                "2;PASCUAL LAURIENTE; >IDA",
                "3;R50 Y LOS BAÑOS; >IDA",
                "4;R50 Y LAS MARGARITAS; >IDA",
                "5;ESCUELA TITARELLI; >IDA",
                "6;R20 Y R33; >IDA",
                "7;R20 Y LOS ALAMOS; >VUELTA",
                "8;R50 Y LOS ALAMOS; >VUELTA",
                "9;R50 Y LOS BAÑOS; >VUELTA",
                "10;PASCUAL LAURIENTE; >VUELTA",
                "11;CONTROL RODEO; >VUELTA"
            ],
            "272": [
                "1;CONTROL RODEO; >IDA",
                "2;ESC. ARGUMEDO; >IDA",
                "3;ESC. SILVANO RODRIGUEZ; >IDA",
                "4;BUENOS AIRES Y SAAVEDRA; >VUELTA",
                "5;COL. SAGRADA FAMILIA; >VUELTA",
                "6;CONTROL RODEO; >VUELTA"
            ],
            "273": [
                "1;CONTROL RODEO; >IDA",
                "2;ARCO; >IDA",
                "3;ESC. ARGUMEDO; >IDA",
                "4;PUENTE DE HIERRO; >IDA",
                "5;ESC. MAESTROS MENDOCINOS; >IDA",
                "6;PUENTE DE HIERRO; >VUELTA",
                "7;SEVERO Y R20; >VUELTA",
                "8;ROTONDA SALCEDO; >VUELTA",
                "9;SEVERO Y ARGUMEDO; >VUELTA",
                "10;CONTROL RODEO; >VUELTA"
            ],
            "274": [
                "1;CONTROL RODEO; >IDA",
                "2;ESC. ARGUMEDO; >IDA",
                "3;ESC. LUGONES; >VUELTA",
                "4;FERRARI Y TABANERA; >VUELTA",
                "5;PUENTE DE HIERRO; >VUELTA",
                "6;CONTROL RODEO; >VUELTA"
            ],
            "275": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;B° LAS CHACRAS; >IDA",
                "3;SEVERO Y SAENZ PEÑA; >IDA",
                "4;ESC. CORSINO; >VUELTA",
                "5;ESC. PESTALOZZI; >VUELTA",
                "6;B° LAS CHACRAS; >VUELTA",
                "7;S.CASTILLO Y GRENON; >VUELTA",
                "8;EL MOLINO; >VUELTA",
                "9;CONTROL CORRALITOS; >VUELTA"
            ],
            "276": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;B° LAS CHACRAS; >IDA",
                "3;SEVERO Y SAENZ PEÑA; >IDA",
                "4;ESC. CORSINO; >IDA",
                "5;ESC. PESTALOZZI; >VUELTA",
                "6;SEVERO Y SAENZ PEÑA; >VUELTA",
                "7;B° LAS CHACRAS; >VUELTA",
                "8;CONTROL CORRALITOS; >VUELTA"
            ],
            "277": [
                "1;CONTROL RODEO; >IDA",
                "2;KM 8; >IDA",
                "3;ACC. ESTE Y R50; >IDA",
                "4;NECOCHEA Y R50; >IDA",
                "5;ESC. PEDRO VARELA; >IDA",
                "6;NECOCHEA Y R50; >IDA",
                "7;PZA Bº 25 DE MAYO; >IDA",
                "8;Bª25 DE JUNIO; >IDA",
                "9;PZA Bº 25 DE MAYO; >VUELTA",
                "10;NECOCHEA Y R50; >VUELTA",
                "11;ESC. PEDRO VARELA; >VUELTA",
                "12;ACC. ESTE Y R50; >VUELTA",
                "13;KM 8; >VUELTA",
                "14;CONTROL RODEO; >VUELTA"
            ],
            "278": [
                "1;CONTROL RODEO; >IDA",
                "2;KM 8; >IDA",
                "3;ACC. ESTE Y R50; >IDA",
                "4;NECOCHEA Y R50; >IDA",
                "5;TROPERO Y NECOCHEA; >VUELTA",
                "6;PZA Bº 25 DE MAYO; >VUELTA",
                "7;NECOCHEA Y R50; >VUELTA",
                "8;ESC. PEDRO VARELA; >VUELTA",
                "9;ACC. ESTE Y R50; >VUELTA",
                "10;KM 8; >VUELTA",
                "11;CONTROL RODEO; >VUELTA"
            ],
            "279": [
                "1;CONTROL RODEO; >IDA",
                "2;KM 8; >IDA",
                "3;ACC. ESTE Y R50; >IDA",
                "4;ESC. PEDRO VARELA; >IDA",
                "5;NECOCHEA Y R50; >IDA",
                "6;PZA Bº 25 DE MAYO; >IDA",
                "7;Bª25 DE JUNIO; >VUELTA",
                "8;NECOCHEA Y R50; >VUELTA",
                "9;ACC. ESTE Y R50; >VUELTA",
                "10;KM 8; >VUELTA",
                "11;CONTROL RODEO; >VUELTA"
            ],
            "280": [
                "1;CONTROL RODEO; >IDA",
                "2;SERPA Y ACCESO ESTE; >IDA",
                "3;ESC. REMEDIOS ESCALADA; >IDA",
                "4;SERPA Y ACCESO ESTE; >VUELTA",
                "5;ESC. PESCARA; >VUELTA",
                "6;CONTROL RODEO; >VUELTA"
            ],
            "281": [
                "1;CONTROL RODEO; >IDA",
                "2;ARCO; >IDA",
                "3;KM 8; >IDA",
                "4;ESC. ISIDRO MAZA; >IDA",
                "5;R50 Y DON BOSCO; >IDA",
                "6;R20 Y DON BOSCO; >VUELTA",
                "7;ESC. ISIDRO MAZA; >VUELTA",
                "8;KM 8; >VUELTA",
                "9;RODEO DE LA CRUZ; >VUELTA",
                "10;CONTROL RODEO; >VUELTA"
            ],
            "282": [
                "1;CONTROL RODEO; >IDA",
                "2;ESC. ISIDRO MAZA; >IDA",
                "3;R50 Y DON BOSCO; >IDA",
                "4;COL. SAGRADA FAMILIA; >VUELTA",
                "5;ESC. ISIDRO MAZA; >VUELTA",
                "6;COL. SAGRADA FAMILIA; >VUELTA",
                "7;R50 Y LOS BAÑOS; >VUELTA",
                "8;KM 8; >VUELTA",
                "9;ARCO; >VUELTA",
                "10;CONTROL RODEO; >VUELTA"
            ],
            "283": [
                "1;CONTROL CORRALITOS; >IDA",
                "2;B° LAS CHACRAS; >IDA",
                "3;SEVERO Y SAENZ PEÑA; >IDA",
                "4;ESC. CORSINO; >VUELTA",
                "5;ESC. PESTALOZZI; >VUELTA",
                "6;SEVERO Y SAENZ PEÑA; >VUELTA",
                "7;B° LAS CHACRAS; >VUELTA",
                "8;CONTROL CORRALITOS; >VUELTA"
            ],
            "284": [
                "1;CONTROL RODEO; >IDA",
                "2;R50 Y DON BOSCO; >IDA",
                "3;ROMA Y DON BOSCO; >IDA",
                "4;DON BOSCO Y SAN MARTIN; >IDA",
                "5;R20 Y DON BOSCO; >IDA",
                "6;BUENOS AIRES Y SAAVEDRA; >IDA",
                "7;R20 Y SERPA; >IDA",
                "8;R50 Y SERPA; >VUELTA",
                "9;R20 Y SERPA; >VUELTA",
                "10;BUENOS AIRES Y SAAVEDRA; >VUELTA",
                "11;R20 Y DON BOSCO; >VUELTA",
                "12;DON BOSCO Y SAN MARTIN; >VUELTA",
                "13;ROMA Y DON BOSCO; >VUELTA",
                "14;R50 Y DON BOSCO; >VUELTA",
                "15;CONTROL RODEO; >VUELTA"
            ],
            "285": [
                "1;CONTROL RODEO; >IDA",
                "2;ESC. MAESTROS MENDOCINOS; >IDA",
                "3;PUENTE DE HIERRO; >VUELTA",
                "4;ESC. ARGUMEDO; >VUELTA",
                "5;CONTROL RODEO; >VUELTA"
            ],
            "286": [
                "1;CONTROL RODEO; >IDA",
                "2;FERRARI Y MILAGROS; >IDA",
                "3;ESC. LUGONES; >IDA",
                "4;ESC. FELIX BOGADO; >IDA",
                "5;ESC. ARGUMEDO; >VUELTA",
                "6;Bº MALVINAS; >VUELTA",
                "7;ESC. MAESTROS MENDOCINOS; >VUELTA",
                "8;CONTROL RODEO; >VUELTA"
            ],
            "287": [
                "1;CONTROL RODEO; >IDA",
                "2;ARCO; >IDA",
                "3;FERRARI Y MILAGROS; >IDA",
                "4;PUENTE DE HIERRO; >IDA",
                "5;ESC. MAESTROS MENDOCINOS; >IDA",
                "6;PUENTE DE HIERRO; >VUELTA",
                "7;FERRARI Y MILAGROS; >VUELTA",
                "8;CONTROL RODEO; >VUELTA"
            ],
            "288": [
                "1;CONTROL RODEO; >IDA",
                "2;ESC. ARGUMEDO; >IDA",
                "3;PUENTE DE HIERRO; >IDA",
                "4;Bº SAN VICENTE; >VUELTA",
                "5;SEVERO Y R20; >VUELTA",
                "6;ESC. ARGUMEDO; >VUELTA",
                "7;CONTROL RODEO; >VUELTA"
            ],
            "289": [
                "1;CONTROL RODEO; >IDA",
                "2;ESC. ARGUMEDO; >IDA",
                "3;PRIMAVERA; >IDA",
                "4;H.PRIMO Y OLASCOAGA; >IDA",
                "5;SEVERO Y R20; >VUELTA",
                "6;ROTONDA SALCEDO; >VUELTA",
                "7;CONTROL RODEO; >VUELTA"
            ],
            "290": [
                "1;CONTROL RODEO; >IDA",
                "2;ESC. ARGUMEDO; >IDA",
                "3;ESC. SILVANO RODRIGUEZ; >IDA",
                "4;BUENOS AIRES Y SAAVEDRA; >VUELTA",
                "5;ESC. SILVANO RODRIGUEZ; >VUELTA",
                "6;CONTROL RODEO; >VUELTA"
            ],
            "291": [
                "1;CONTROL RODEO; >IDA",
                "2;ESC. ARGUMEDO; >IDA",
                "3;ESC. SILVANO RODRIGUEZ; >VUELTA",
                "4;COL. SAGRADA FAMILIA; >VUELTA",
                "5;CONTROL RODEO; >VUELTA"
            ],
            "292": [
                "1;SALIDA TERMINAL; >IDA",
                "2;ESC SARMIENTO; >VUELTA",
                "3;B. SUR MER (LOCALES); >VUELTA",
                "4;ROTONDA ORZALI.; >VUELTA",
                "5;Bª LA FAVORITA; >VUELTA",
                "6;SALIDA TERMINAL; >VUELTA"
            ],
            "293": [
                "1;SALIDA TERMINAL; >IDA",
                "2;Bª LA FAVORITA; >VUELTA",
                "3;SALA 1º AUXILIOS; >VUELTA",
                "4;ROTONDA ORZALI; >VUELTA",
                "5;ESC. EVA PERON; >VUELTA",
                "6;SALIDA TERMINAL; >VUELTA"
            ],
            "294": [
                "1;CONTROL RODEO; >IDA",
                "2;SERPA Y ACCESO ESTE; >IDA",
                "3;ESC. PESCARA; >IDA",
                "4;ESC. REMEDIOS ESCALADA; >VUELTA",
                "5;SERPA Y ACCESO ESTE; >VUELTA",
                "6;CONTROL RODEO; >VUELTA"
            ],
            "295": [
                "1;CONTROL RODEO; >IDA",
                "2;SERPA Y ACCESO ESTE; >IDA",
                "3;ESC. PESCARA; >IDA",
                "4;ESC. REMEDIOS ESCALADA; >VUELTA",
                "5;SERPA Y ACCESO ESTE; >VUELTA",
                "6;CONTROL RODEO; >VUELTA"
            ],
            "296": [
                "1;CONTROL RODEO; >IDA",
                "2;SERPA Y ACCESO ESTE; >IDA",
                "3;ESC. REMEDIOS ESCALADA; >VUELTA",
                "4;SERPA Y ACCESO ESTE; >VUELTA",
                "5;CONTROL RODEO; >VUELTA"
            ],
            "297": [
                "1;SALIDA TERMINAL; >IDA",
                "2;Bª LA FAVORITA; >IDA",
                "3;Bº OLIVARES; >VUELTA",
                "4;ESC. VIDELA CORREA; >VUELTA",
                "5;SALIDA TERMINAL; >VUELTA"
            ],
            "298": [
                "1;CONTROL RODEO; >IDA",
                "2;ESC. ARGUMEDO; >IDA",
                "3;PONCE Y BANDERA; >IDA",
                "4;GODOY CRUZ Y BUENOS VECINOS; >IDA",
                "5;ESC. LUGONES; >IDA",
                "6;SANCHEZ Y BUENOS AIRES; >IDA",
                "7;FERRARI Y BUENOS VECINOS; >IDA",
                "8;SEVERO Y FERRARI; >IDA",
                "9;CONTROL CORRALITOS; >VUELTA",
                "10;CONTROL CORRALITOS; >VUELTA",
                "11;SEVERO Y FERRARI; >VUELTA",
                "12;FERRARI Y BUENOS VECINOS; >VUELTA",
                "13;SANCHEZ Y BUENOS AIRES; >VUELTA",
                "14;ESC. LUGONES; >VUELTA",
                "15;GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "16;PONCE Y BANDERA; >VUELTA",
                "17;CONTROL RODEO; >VUELTA"
            ]
        
        }
    }
};