const DB_RECORRIDOS = {
"G800": {
        
    "recorridos": {

    "FUERA-DE-SERVICIO": [
    ],
    "CONTROL-SAN-MARTIN-Y-5-ABRIL": [
    ],
    "CONTROL-TROPERO-Y-5-ABRIL": [
    ],
    "QUEDA-B-AMUPE": [
    ],
    "QUEDA-EST.GUTIERREZ": [
    ],
    "CONTROL-RODEO": [
    ],
    "QUEDA-RECOARO": [
    ],
    "QUEDA-B-C.SOÑADA": [
    ],
    "1873": [
        "8-ESTACION GUTIERREZ; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-RUSSELL; >IDA",
        "8-CRUZ DE PIEDRA; >IDA",
        "8-TRES ESQUINAS (ESC. CRUZ DE PIEDRA); >IDA",
        "8-LUNLUNTA; >VUELTA",
        "8-CRUZ DE PIEDRA; >VUELTA",
        "8-RUSSELL; >VUELTA",
        "8-MAIPU (PERON); >VUELTA",
        "8-ESTACION GUTIERREZ; >VUELTA"
    ],
    "801": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-CANCILLER (PEZZUTTI Y LEANEZ); >IDA",
        "8-LAT. E.CIVIT Y VIEYTES; >IDA",
        "8-PALMA Y OZAMIS; >IDA",
        "8-VIEYTES Y R60; >IDA",
        "8-CARBOMETAL; >VUELTA",
        "8-VIEYTES Y R60; >VUELTA",
        "8-PALMA Y OZAMIS; >VUELTA",
        "8-LAT. E.CIVIT Y VIEYTES; >VUELTA",
        "8-CANCILLER (PEZZUTTI Y LEANEZ); >VUELTA",
        "8-MAIPU (MUNICIPALIDAD); >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "802": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-ROTONDA BOMBEROS; >IDA",
        "8-VIEYTES Y BOEDO; >IDA",
        "8-EL CIRCUITO; >IDA",
        "8-BULNES Y SAN MARTIN; >VUELTA",
        "8-CARBOMETAL; >VUELTA",
        "8-VIEYTES Y BOEDO; >VUELTA",
        "8-ROTONDA BOMBEROS; >VUELTA",
        "8-MAIPU (MUNICIPALIDAD); >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "803": [
        "8-CONTROL MAIPU; >IDA",
        "8-OZAMIS Y 25 DE MAYO; >IDA",
        "8-VIEYTES Y V. CASTILLO; >IDA",
        "8-PASO Y ACCESO SUR; >IDA",
        "8-TERMINAL; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-PASO Y ACCESO SUR; >VUELTA",
        "8-VIEYTES Y V. CASTILLO; >VUELTA",
        "8-OZAMIS Y 25 DE MAYO; >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ], // Se omitió: HTAL ITALIANO (DIFERENCIAL)
    "804": [
        "8-CONTROL MAIPU; >IDA",
        "8-OZAMIS Y 25 DE MAYO; >IDA",
        "8-VIEYTES Y V. CASTILLO; >IDA",
        "8-PASO Y TERRADA; >IDA",
        "8-RAWSON Y ACC.SUR; >IDA",
        "8-PTE OLIVE IDA; >IDA",
        "8-PZA GODOY CRUZ IDA; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-PZA GODOY CRUZ (VUELTA); >VUELTA",
        "8-PTE OLIVE VUELTA; >VUELTA",
        "8-RAWSON Y ACC.SUR; >VUELTA",
        "8-PASO Y TERRADA; >VUELTA",
        "8-VIEYTES Y V. CASTILLO; >VUELTA",
        "8-OZAMIS Y 25 DE MAYO; >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ], // Se omitió: TERMINAL
    "810": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-URQUIZA Y ZANICHELLI; >IDA",
        "8-R. PEÑA Y URQUIZA; >IDA",
        "8-R. PEÑA Y GABRIELLI; >IDA",
        "8-PZA GODOY CRUZ IDA; >IDA",
        "8-TERMINAL; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-LIBERTAD Y GODOY CRUZ; >VUELTA",
        "8-RODEO DE LA CRUZ; >VUELTA",
        "8-GOMEZ Y URQUIZA; >VUELTA",
        "8-OZAMIS Y CORREA; >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "811": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-URQUIZA Y ZANICHELLI; >IDA",
        "8-R. PEÑA Y URQUIZA; >IDA",
        "8-R. PEÑA Y GABRIELLI; >IDA",
        "8-PZA GODOY CRUZ IDA; >IDA",
        "8-TERMINAL; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-LIBERTAD Y GODOY CRUZ; >VUELTA",
        "8-RODEO DE LA CRUZ; >VUELTA",
        "8-GOMEZ Y URQUIZA; >VUELTA",
        "8-URQUIZA Y ZANICHELLI; >VUELTA",
        "8-G.CRUZ Y BARCALA; >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "812": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-P. VAZQUEZ Y CORREA; >IDA",
        "8-R. PEÑA Y URQUIZA; >IDA",
        "8-KM 14; >IDA",
        "8-LIBERTAD Y GODOY CRUZ; >IDA",
        "8-MITRE Y G. CRUZ; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-PZA GODOY CRUZ (VUELTA); >VUELTA",
        "8-R. PEÑA Y GABRIELLI; >VUELTA",
        "8-GOMEZ Y URQUIZA; >VUELTA",
        "8-URQUIZA Y ZANICHELLI; >VUELTA",
        "8-G.CRUZ Y BARCALA; >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "813": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-URQUIZA Y ZANICHELLI; >IDA",
        "8-R. PEÑA Y URQUIZA; >IDA",
        "8-KM 14; >IDA",
        "8-LIBERTAD Y GODOY CRUZ; >IDA",
        "8-MITRE Y G. CRUZ; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-PZA GODOY CRUZ (VUELTA); >VUELTA",
        "8-R. PEÑA Y GABRIELLI; >VUELTA",
        "8-GOMEZ Y URQUIZA; >VUELTA",
        "8-URQUIZA Y ZANICHELLI; >VUELTA",
        "8-G.CRUZ Y BARCALA; >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "814": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-TROPERO Y NECOCHEA; >IDA",
        "8-ORTEGA; >IDA",
        "8-ESC. F. PELAEZ; >IDA",
        "8-ESC. F. PELAEZ; >VUELTA",
        "8-ORTEGA; >VUELTA",
        "8-TROPERO Y NECOCHEA; >VUELTA",
        "8-MAIPU (HOSPITAL); >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "815": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-URQUIZA Y ZANICHELLI; >IDA",
        "8-GOMEZ Y URQUIZA; >IDA",
        "8-R. PEÑA Y GABRIELLI; >IDA",
        "8-TERMINAL; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-R. PEÑA Y GABRIELLI; >VUELTA",
        "8-GOMEZ Y URQUIZA; >VUELTA",
        "8-URQUIZA Y ZANICHELLI; >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "816": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-URQUIZA Y ZANICHELLI; >IDA",
        "8-GOMEZ Y URQUIZA; >IDA",
        "8-R. PEÑA Y URQUIZA; >IDA",
        "8-TERMINAL; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-R. PEÑA Y URQUIZA; >VUELTA",
        "8-GOMEZ Y URQUIZA; >VUELTA",
        "8-URQUIZA Y ZANICHELLI; >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],

    "817": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (MUNICIPALIDAD); >IDA",
        "8-MAITEN; >IDA",
        "8-BOEDO Y CORREA; >IDA",
        "8-GOMEZ Y URQUIZA; >IDA",
        "8-R. PEÑA Y URQUIZA; >IDA",
        "8-TERMINAL; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-R. PEÑA Y URQUIZA; >VUELTA",
        "8-GOMEZ Y URQUIZA; >VUELTA",
        "8-BOEDO Y CORREA; >VUELTA",
        "8-MAITEN; >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "818": [
        "8-CONTROL-MAIPÚ; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-P. VAZQUEZ Y CORREA; >IDA",
        "8-CANAL PESCARA; >IDA",
        "8-R. PEÑA Y URQUIZA; >IDA",
        "8-V. VIÑEDO; >IDA",
        "8-Bº PICCIONE; >VUELTA",
        "8-V. VIÑEDO; >VUELTA",
        "8-CANAL PESCARA; >VUELTA",
        "8-OZAMIS Y CORREA; >VUELTA",
        "8-CONTROL-MAIPÚ; >VUELTA"
    ],
    "819": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-URQUIZA Y ZANICHELLI; >IDA",
        "8-ESC. F. PELAEZ; >VUELTA",
        "8-URQUIZA Y ZANICHELLI; >VUELTA",
        "8-MAIPU (HOSPITAL); >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "820": [
        "8-AMUPE (P. Moreno y Saavedra); >IDA",
        "8-B° T. SOSA; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-B° CANCILLER; >IDA",
        "8-MAZA Y J.B. JUSTO; >IDA",
        "8-MAZA Y SARMIENTO; >IDA",
        "8-VARIANTE Y SARMIENTO; >IDA",
        "8-PTE OLIVE IDA; >IDA",
        "8-PZA GODOY CRUZ IDA; >IDA",
        "8-TERMINAL; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-PZA GODOY CRUZ (VUELTA); >VUELTA",
        "8-PTE OLIVE VUELTA; >VUELTA",
        "8-VARIANTE Y SARMIENTO; >VUELTA",
        "8-MAZA Y SARMIENTO; >VUELTA",
        "8-MAZA Y J.B. JUSTO; >VUELTA",
        "8-B° CANCILLER; >VUELTA",
        "8-MAIPU (MUNICIPALIDAD); >VUELTA",
        "8-B° T. SOSA; >VUELTA",
        "8-AMUPE (P. Moreno y Saavedra); >VUELTA"
    ],
    "821": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (MUNICIPALIDAD); >IDA",
        "8-MAZA Y SARMIENTO; >IDA",
        "8-SARMIENTO Y ACC. SUR; >IDA",
        // Se excluyó HTAL ITALIANO (DIFERENCIAL) por planilla NO
        "8-TERMINAL; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-SARMIENTO Y ACC. SUR; >VUELTA",
        "8-MAZA Y SARMIENTO; >VUELTA",
        "8-OZAMIS Y 60 GRANADEROS; >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "823": [
	"8-AMUPE (P. Moreno y Saavedra); >IDA",
        "8-B° T. SOSA; >IDA",
        "8-MAIPU (PERON);  >IDA",
        "8-B° CANCILLER; >IDA",
        "8-MAZA Y J.B. JUSTO; >IDA",
        "8-MAZA Y SARMIENTO; >IDA",
        "8-VARIANTE Y SARMIENTO; >IDA",
        "8-SARMIENTO Y ACC. SUR; >IDA",
        "8-TERMINAL; >IDA",
        "8-PEDRO MOLINA Y SAN MARTIN; >VUELTA",
        "8-SARMIENTO Y ACC. SUR; >VUELTA",
        "8-VARIANTE Y SARMIENTO; >VUELTA",
        "8-MAZA Y SARMIENTO; >VUELTA",
        "8-MAZA Y J.B. JUSTO; >VUELTA",
        "8-B° CANCILLER; >VUELTA",
        "8-MAIPU (HOSPITAL); >VUELTA",
        "8-B° T. SOSA; >VUELTA",
        "8-AMUPE (P. Moreno y Saavedra); >VUELTA"
    ],
    "824": [
        "8-AMUPE (P. Moreno y Saavedra); >IDA",
        "8-B° T. SOSA; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-B° CANCILLER; >IDA",
        "8-MAZA Y J.B. JUSTO; >IDA",
        "8-MAZA Y SARMIENTO; >IDA",
        "8-VARIANTE Y SARMIENTO; >IDA",
        "8-PTE OLIVE IDA; >IDA",
        "8-PZA GODOY CRUZ IDA; >IDA",
        "8-TERMINAL; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-PZA GODOY CRUZ (COLON); >VUELTA",
        "8-PTE OLIVE VUELTA; >VUELTA",
        "8-VARIANTE Y SARMIENTO; >VUELTA",
        "8-MAZA Y SARMIENTO; >VUELTA",
        "8-MAZA Y J.B. JUSTO; >VUELTA",
        "8-B° CANCILLER; >VUELTA",
        "8-MAIPU (HOSPITAL); >VUELTA",
        "8-B° T. SOSA; >VUELTA",
        "8-AMUPE (P. Moreno y Saavedra); >VUELTA"
    ],
    "825": [
	   "8-CONTROL  MAIPU; >IDA",
           "8-T. SOSA Y URQUIZA; >IDA",
           "8-Bº 25 DE MAYO; >IDA",
           "8-T. SOSA Y URQUIZA; >IDA",
           "8-MAIPU (HOSPITAL); >IDA",
           "8-P. VAZQUEZ Y CORREA; >IDA",
           "8-VARIANTE (PTE HIERRO); >IDA",
           "8-VARIANTE Y SARMIENTO; >VUELTA",
           "8-VARIANTE (PTE HIERRO); >VUELTA",
           "8-OZAMIS Y CORREA; >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "830": [
           "8-ESTACION GUTIERREZ.; >IDA",
           "8-OZAMIS Y CORREA; >IDA",
           "8-OZAMIS Y 60 GRANADEROS; >IDA",
           "8-RUSSELL; >IDA",
           "8-CRUZ DE PIEDRA; >IDA",
           "8-RECOARO; >IDA",
           "8-LUNLUNTA; >IDA",
           "8-SAENZ PEÑA Y GUIÑAZU; >VUELTA",
           "8-MUSEO DE FADER; >VUELTA",
           "8-RUSSELL; >VUELTA",
           "8-LA SUPERIORA; >VUELTA",
           "8-MAIPU (PERON); >VUELTA",
           "8-P. VAZQUEZ Y CORREA; >VUELTA",
           "8-CANAL PESCARA; >VUELTA",
           "8-BELGRANO Y ACCESO ESTE; >VUELTA",
           "8-R. PEÑA Y URQUIZA; >VUELTA",
           "8-CONTROL RODEO; >VUELTA"
    ],
    "840": [
           "8-CONTROL RODEO; >IDA",
           "8-R. PEÑA Y URQUIZA; >IDA",
           "8-BELGRANO Y ACCESO ESTE; >IDA",
           "8-CANAL PESCARA; >IDA",
           "8-OZAMIS Y CORREA; >IDA",
           "8-OZAMIS Y 60 GRANADEROS; >IDA",
           "8-LA SUPERIORA; >IDA",
           "8-RUSSELL; >IDA",
           "8-MUSEO DE FADER; >IDA",
           "8-SAENZ PEÑA Y GUIÑAZU; >VUELTA",
           "8-LUNLUNTA; >VUELTA",
           "8-RECOARO; >VUELTA",
           "8-CRUZ DE PIEDRA; >VUELTA",
           "8-RUSSELL; >VUELTA",
           "8-MAIPU (PERON); >VUELTA",
           "8-P. VAZQUEZ Y CORREA; >VUELTA"
    ],
    "850": [
           "8-CONTROL  MAIPU; >IDA",
           "8-P. VAZQUEZ Y CORREA; >IDA",
           "8-GOMEZ Y CANAL PESCARA; >IDA",
           "8-ORTEGA; >IDA",
           "8-NECOCHEA Y R50; >IDA",
           "8-Bº LOS SOLARES; >IDA",
           "8-CARRIL VIEJO Y RESPLANDOR; >IDA",
           "8-R60 Y NAZAR; >IDA",
           "8-Bº JARDIN RODEO; >IDA",
           "8-ESC. DON BOSCO; >VUELTA",
           "8-R60 Y PUEYRREDON; >VUELTA",
           "8-R60 Y NAZAR; >VUELTA",
           "8-CARRIL VIEJO Y RESPLANDOR; >VUELTA",
           "8-Bº LOS SOLARES; >VUELTA",
           "8-NECOCHEA Y R50; >VUELTA",
           "8-ORTEGA; >VUELTA",
           "8-GOMEZ Y CANAL PESCARA; >VUELTA",
           "8-OZAMIS Y CORREA; >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "852": [
           "8-ESTACION GUTIERREZ; >IDA",
           "8-OZAMIS Y 60 GRANADEROS; >IDA",
           "8-T. SOSA Y URQUIZA; >IDA",
           "8-URQUIZA Y R60; >IDA",
           "8-R60 Y PUEYRREDON; >IDA",
           "8-R60 Y F. PIPERBO; >IDA",
           "8-BARRIALES LLEGADA; >IDA",
           "8-BARRIALES; >VUELTA",
           "8-R60 Y F. PIPERBO; >VUELTA",
           "8-R60 Y PUEYRREDON; >VUELTA",
           "8-URQUIZA Y R60; >VUELTA",
           "8-T. SOSA Y URQUIZA; >VUELTA",
           "8-MAIPU (PERON); >VUELTA",
           "8-ESTACION GUTIERREZ; >VUELTA"
    ],
    "853": [
           "8-CONTROL  MAIPU; >IDA",
           "8-T. SOSA Y URQUIZA; >IDA",
           "8-URQUIZA Y R60; >IDA",
           "8-R60 Y NAZAR; >IDA",
           "8-URQUIZA Y R60; >IDA",
           "8-T. SOSA Y URQUIZA; >IDA",
           "8-MAIPU (PERON); >IDA",
           "8-VARIANTE (PTE HIERRO); >IDA",
           "8-VARIANTE Y SARMIENTO; >VUELTA",
           "8-ESC. ALFONSINA STORNI; >VUELTA",
           "8-VARIANTE (PTE HIERRO); >VUELTA",
           "8-MAIPU (MUNICIPALIDAD); >VUELTA",
           "8-B° T. SOSA; >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "854": [
           "8-CONTROL  MAIPU; >IDA",
           "8-MAIPU (MUNICIPALIDAD); >IDA",
           "8-URQUIZA Y P.MORENO; >IDA",
           "8-P.MORENO Y PUEYRREDON; >IDA",
           "8-Bº JARDIN RODEO; >IDA",
           "8-R50 Y DON BOSCO; >IDA",
           "8-R50 Y LOS ALAMOS (ALVAREZ); >IDA",
           "8-R50 Y LAMADRID; >VUELTA",
           "8-CARRIL VIEJO Y LAMADRID; >VUELTA",
           "8-CARRIL VIEJO Y RESPLANDOR; >VUELTA",
           "8-P.MORENO Y PUEYRREDON; >VUELTA",
           "8-URQUIZA Y P.MORENO; >VUELTA",
           "8-TROPERO Y G.CRUZ; >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "855": [
           "8-CONTROL  MAIPU; >IDA",
           "8-MAIPU (MUNICIPALIDAD); >IDA",
           "8-URQUIZA Y P.MORENO; >IDA",
           "8-P.MORENO Y PUEYRREDON; >IDA",
           "8-CARRIL VIEJO Y RESPLANDOR; >IDA",
           "8-CARRIL VIEJO Y LAMADRID; >VUELTA",
           "8-R50 Y LAMADRID; >VUELTA",
           "8-R50 Y LOS ALAMOS (ALVAREZ); >VUELTA",
           "8-R50 Y DON BOSCO; >VUELTA",
           "8-Bº JARDIN RODEO; >VUELTA",
           "8-P.MORENO Y PUEYRREDON; >VUELTA",
           "8-URQUIZA Y P.MORENO; >VUELTA",
           "8-TROPERO Y G.CRUZ; >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "856": [
           "8-CONTROL  MAIPU; >IDA",
           "8-MAIPU (MUNICIPALIDAD); >IDA",
           "8-T. SOSA Y URQUIZA; >IDA",
           "8-URQUIZA Y R60; >IDA",
           "8-ESC. JOSE ALVAREZ; >IDA",
           "8-R60 Y PUEYRREDON; >IDA",
           "8-C.VIEJO Y ZANETTI; >IDA",
           "8-R60 Y F. PIPERBO; >IDA",
           "8-GARDELA Y R60; >IDA",
           "8-LA COSTA Y R60; >IDA",
           "8-BARRIALES; >VUELTA",
           "8-LA COSTA Y R60; >VUELTA",
           "8-GARDELA Y R60; >VUELTA",
           "8-R60 Y F. PIPERBO; >VUELTA",
           "8-C.VIEJO Y ZANETTI; >VUELTA",
           "8-R60 Y PUEYRREDON; >VUELTA",
           "8-ESC. JOSE ALVAREZ; >VUELTA",
           "8-URQUIZA Y R60; >VUELTA",
           "8-T. SOSA Y URQUIZA; >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "857": [
           "8-ESTACION GUTIERREZ; >IDA",
           "8-OZAMIS Y 60 GRANADEROS; >IDA",
           "8-T. SOSA Y URQUIZA; >IDA",
           "8-URQUIZA Y R60; >IDA",
           "8-R60 Y PUEYRREDON; >IDA",
           "8-R60 Y F. PIPERBO; >IDA",
           "8-BARRIALES; >IDA",
           "8-JUNIN; >VUELTA",
           "8-BARRIALES; >VUELTA",
           "8-R60 Y F. PIPERBO; >VUELTA",
           "8-R60 Y PUEYRREDON; >VUELTA",
           "8-URQUIZA Y R60; >VUELTA",
           "8-T. SOSA Y URQUIZA; >VUELTA",
           "8-MAIPU (PERON); >VUELTA",
           "8-ESTACION GUTIERREZ; >VUELTA"
    ],
    "860": [
           "8-ESTACION GUTIERREZ; >IDA",
           "8-MAIPU (PERON); >IDA",
           "8-RUSSELL; >IDA",
           "8-CRUZ DE PIEDRA; >IDA",
           "8-TRES ESQUINAS (V.ARANDA); >IDA",
           "8-LUNLUNTA; >VUELTA",
           "8-SAN GABRIEL - SAN ZENON (RECOARO); >VUELTA",
           "8-CRUZ DE PIEDRA; >VUELTA",
           "8-RUSSELL; >VUELTA",
           //"8-MAIPU (MUNICIPALIDAD); >VUELTA", SE QUITA ESTA ESTAPA PORQUE ES DE CONTROL
           "8-MAIPU (PERON); >VUELTA",
           "8-ESTACION GUTIERREZ; >VUELTA"
    ],
    "861": [
        "8-ESTACION GUTIERREZ; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-RUSSELL; >IDA",
        "8-CRUZ DE PIEDRA; >IDA",
        "8-SAN GABRIEL - SAN ZENON (RECOARO); >IDA",
        "8-LUNLUNTA; >VUELTA",
        "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
        "8-CRUZ DE PIEDRA; >VUELTA",
        "8-RUSSELL; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "8-MAIPU (PERON); >VUELTA",
        "8-ESTACION GUTIERREZ; >VUELTA"
    ],
    "863": [
        "8-Bº CICERONI; >IDA",
        "8-CRUZ DE PIEDRA; >IDA",
        "8-MAIPU (MUNICIPALIDAD); >IDA",
        "8-MAZA Y SARMIENTO; >IDA",
        "8-SARMIENTO Y ACC. SUR; >IDA",
        // Se excluyó HTAL ITALIANO (DIFERENCIAL) por planilla NO
        "8-TERMINAL; >VUELTA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-SARMIENTO Y ACC. SUR; >VUELTA",
        "8-MAZA Y SARMIENTO; >VUELTA",
        "8-OZAMIS Y 60 GRANADEROS; >VUELTA",
        "8-CRUZ DE PIEDRA; >VUELTA",
        "8-Bº CICERONI; >VUELTA"
    ],
    "864": [
        "8-ESTACION GUTIERREZ; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-LA SUPERIORA; >IDA",
        "8-RUSSELL; >IDA",
        "8-TRES ESQUINAS (V.ARANDA); >IDA",
        "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
        "8-RUSSELL; >VUELTA",
        "8-LA SUPERIORA; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "8-MAIPU (PERON); >VUELTA",
        "8-ESTACION GUTIERREZ; >VUELTA"
    ],
    "865": [
        "8-AMUPE (P. Y URQUIZA); >IDA",
        "8-TRES ESQUINAS (V.ARANDA); >IDA",
        "8-CRUZ DE PIEDRA (C.VIDELA Y OZAMIS); >IDA",
        "8-RUSSELL; >IDA",
        "8-LA SUPERIORA; >IDA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en IDA
        "8-MAIPU (PERON); >IDA",
        "8-VARIANTE (PTE HIERRO); >IDA",
        "8-VARIANTE Y SARMIENTO; >IDA",
        "8-ACCESO SUR Y R.PEÑA; >IDA",
        "8-TERMINAL; >VUELTA",
        "8-PEDRO MOLINA Y SAN MARTIN; >VUELTA",
        "8-ACCESO SUR Y R.PEÑA; >VUELTA",
        "8-VARIANTE Y SARMIENTO; >VUELTA",
        "8-VARIANTE (PTE HIERRO); >VUELTA",
        "8-MAIPU (HOSPITAL); >VUELTA",
        "8-Bº MALCAYAES; >VUELTA",
        "8-B° T. SOSA; >VUELTA",
        "8-AMUPE (P. Y URQUIZA); >VUELTA"
    ],
    "866": [
           "8-AMUPE (P. Moreno y Saavedra); >IDA",
           "8-B° T. SOSA; >IDA",
           "8-Bº MALCAYAES; >IDA",
           "8-MAIPU (PERON); >IDA",
           "8-VARIANTE (PTE HIERRO); >IDA",
           "8-VARIANTE Y SARMIENTO; >IDA",
           "8-ACCESO SUR Y R.PEÑA; >IDA",
           "8-TERMINAL; >IDA",
           "8-PEDRO MOLINA Y SAN MARTIN; >VUELTA",
           "8-ACCESO SUR Y R.PEÑA; >VUELTA",
           "8-VARIANTE Y SARMIENTO; >VUELTA",
           "8-VARIANTE (PTE HIERRO); >VUELTA",
           "8-MAIPU (PERON); >VUELTA",
           "8-LA SUPERIORA; >VUELTA",
           "8-RUSSELL; >VUELTA",
           "8-CRUZ DE PIEDRA (C.VIDELA Y OZAMIS); >VUELTA",
           "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
           "8-AMUPE (P. Moreno y Saavedra); >VUELTA"
    ],
    "867": [
        "8-TRES ESQUINAS (ESC. CRUZ DE PIEDRA); >IDA",
        "8-CRUZ DE PIEDRA; >IDA",
        "8-MAIPU (MUNICIPALIDAD); >IDA",
        "8-MAZA Y SARMIENTO; >IDA",
        "8-SARMIENTO Y ACC. SUR; >IDA",
        // Se excluyó HTAL ITALIANO (DIFERENCIAL) por planilla NO
        "8-TERMINAL; >VUELTA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        "8-SARMIENTO Y ACC. SUR; >VUELTA",
        "8-MAZA Y SARMIENTO; >VUELTA",
        "8-OZAMIS Y 60 GRANADEROS; >VUELTA",
        "8-CRUZ DE PIEDRA; >VUELTA",
        "8-TRES ESQUINAS (ESC. CRUZ DE PIEDRA); >VUELTA"
    ],
    "868": [
           "8-CONTROL  MAIPU; >IDA",
           "8-MAIPU (PERON); >IDA",
           "8-RUSSELL; >IDA",
           "8-CRUZ DE PIEDRA; >IDA",
           "8-Bº CICERONI; >IDA",
           "8-LUNLUNTA; >IDA",
           "8-CRUZ DE PIEDRA; >VUELTA",
           "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
           "8-LUNLUNTA; >VUELTA",
           "8-CRUZ DE PIEDRA; >VUELTA",
           "8-RUSSELL; >VUELTA",
           "8-MAIPU (MUNICIPALIDAD); >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "869": [
           "8-CONTROL  MAIPU; >IDA",
           "8-MAIPU (MUNICIPALIDAD); >IDA",
           "8-T. SOSA Y URQUIZA; >IDA",
           "8-SUTE; >VUELTA",
           "8-T. SOSA Y URQUIZA; >VUELTA",
           "8-MAIPU (MUNICIPALIDAD); >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "870": [
        "8-CONTROL MAIPU; >IDA",
        "8-MAIPU (MUNICIPALIDAD); >IDA",
        // Se excluyó URQUIZA Y P.MORENO por planilla NO en IDA
        "8-TRES ESQUINAS (V.ARANDA); >IDA",
        "8-R14 Y CALLE NUEVA; >IDA",
        "8-LA CAPILLA Y SIMONOVICH; >IDA",
        "8-BRISAS DEL RIO; >IDA",
        "8-R14 Y SIMONOVICH; >IDA",
        "8-JUMEN; >IDA",
        "8-ESCUELA J. ESPADA; >VUELTA",
        "8-JUMEN; >VUELTA",
        "8-R14 Y SIMONOVICH; >VUELTA",
        "8-BRISAS DEL RIO; >VUELTA",
        "8-LA CAPILLA Y SIMONOVICH; >VUELTA",
        "8-R14 Y CALLE NUEVA; >VUELTA",
        "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
        "8-TROPERO Y G.CRUZ; >VUELTA",
        "8-CONTROL MAIPU; >VUELTA"
    ],
    "871": [
        "8-ESTACION GUTIERREZ; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-RUSSELL; >IDA",
        "8-CRUZ DE PIEDRA; >IDA",
        "8-TRES ESQUINAS (V.ARANDA); >IDA",
        "8-R14 Y CALLE NUEVA; >IDA",
        "8-LA CAPILLA Y SIMONOVICH; >IDA",
        "8-R14 Y SIMONOVICH; >IDA",
        "8-JUMEN; >IDA",
        "8-ESCUELA J. ESPADA; >VUELTA",
        "8-JUMEN; >VUELTA",
        "8-R14 Y SIMONOVICH; >VUELTA",
        "8-LA CAPILLA Y SIMONOVICH; >VUELTA",
        "8-R14 Y CALLE NUEVA; >VUELTA",
        "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
        "8-CRUZ DE PIEDRA; >VUELTA",
        "8-RUSSELL; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "8-MAIPU (PERON); >VUELTA",
        "8-ESTACION GUTIERREZ; >VUELTA"
    ],
    "872": [
        "8-ESTACION GUTIERREZ; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-LA SUPERIORA; >IDA",
        "8-RUSSELL; >IDA",
        "8-TRES ESQUINAS (V.ARANDA); >IDA",
        "8-R14 Y CALLE NUEVA; >IDA",
        "8-LA CAPILLA Y SIMONOVICH; >IDA",
        "8-R14 Y SIMONOVICH; >IDA",
        "8-JUMEN; >IDA",
        "8-ESCUELA J. ESPADA; >VUELTA",
        "8-JUMEN; >VUELTA",
        "8-R14 Y SIMONOVICH; >VUELTA",
        "8-LA CAPILLA Y SIMONOVICH; >VUELTA",
        "8-R14 Y CALLE NUEVA; >VUELTA",
        "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
        "8-RUSSELL; >VUELTA",
        "8-LA SUPERIORA; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "8-MAIPU (PERON); >VUELTA",
        "8-ESTACION GUTIERREZ; >VUELTA"
    ],
    "880": [
        "8-ESTACION GUTIERREZ; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-RUSSELL; >IDA",
        "8-CRUZ DE PIEDRA; >IDA",
        "8-TRES ESQUINAS (V.ARANDA); >IDA",
        "8-CHACHINGO; >IDA",
        "8-PUEYRREDON Y U.VECINAL; >VUELTA",
        "8-CHACHINGO; >VUELTA",
        "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
        "8-CRUZ DE PIEDRA; >VUELTA",
        "8-RUSSELL; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "8-MAIPU (PERON); >VUELTA",
        "8-ESTACION GUTIERREZ; >VUELTA"
    ],
    "881": [
        "8-ESTACION GUTIERREZ; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-LA SUPERIORA; >IDA",
        "8-RUSSELL; >IDA",
        "8-CRUZ DE PIEDRA; >IDA",
        "8-TRES ESQUINAS (V.ARANDA); >IDA",
        "8-CHACHINGO; >IDA",
        "8-PUEYRREDON Y U.VECINAL; >IDA",
        "8-CHACHINGO; >VUELTA",
        "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
        "8-CRUZ DE PIEDRA; >VUELTA",
        "8-RUSSELL; >VUELTA",
        "8-LA SUPERIORA; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "8-MAIPU (PERON); >VUELTA",
        "8-ESTACION GUTIERREZ; >VUELTA"
    ],
    "890": [

           "8-CONTROL  MAIPU; >IDA",
           "8-Bº MALCAYAES; >IDA",
           "8-CELINA ALVAREZ; >VUELTA",
           "8-MAIPU (ESC.OZAMIS); >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "891": [
           "8-CONTROL  MAIPU; >IDA",
           "8-CELINA ALVAREZ; >IDA",
           "8-MAIPU (ESC.OZAMIS); >IDA",
           "8-MAITEN; >VUELTA",
           "8-Bº MALCAYAES; >VUELTA",
           "8-ESC. AGUIRRE; >VUELTA",
           "8-CELINA ALVAREZ; >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "892": [
           "8-CONTROL  MAIPU; >IDA",
           "8-ESC. OZAMIS; >IDA",
           "8-CELINA ALVAREZ; >IDA",
           "8-ESC. AGUIRRE; >VUELTA",
           "8-MAITEN; >VUELTA",
           "8-Bº MALCAYAES; >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "893": [
           "8-CONTROL  MAIPU; >IDA",
           "8-MAIPU (MUNICIPALIDAD); >IDA",
           "8-URQUIZA Y ZANICHELLI; >IDA",
           "8-GOMEZ Y URQUIZA; >IDA",
           "8-R. PEÑA Y URQUIZA; >VUELTA",
           "8-MAZA Y SARMIENTO; >VUELTA",
           "8-OZAMIS Y CORREA; >VUELTA",
           "8-CONTROL  MAIPU; >VUELTA"
    ],
    "896": [
        "8-AMUPE (P. Y URQUIZA); >IDA",
        "8-TRES ESQUINAS (V.ARANDA); >IDA",
        "8-CRUZ DE PIEDRA; >IDA",
        "8-TERRADA Y R60; >IDA",
        // Se excluyeron PASO Y ACCESO SUR y SARMIENTO Y ACC. SUR por planilla NO en IDA
        "8-TERMINAL; >IDA",
        "8-CATAMARCA Y RIOJA; >VUELTA",
        // Se excluyeron SARMIENTO Y ACC. SUR y PASO Y ACCESO SUR por planilla NO en VUELTA
        "8-TERRADA Y R60; >VUELTA",
        "8-CRUZ DE PIEDRA; >VUELTA",
        "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
        "8-AMUPE (P. Y URQUIZA); >VUELTA"
    ],
    "897": [
        "8-ESTACION GUTIERREZ; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-RUSSELL; >IDA",
        "8-CRUZ DE PIEDRA; >IDA",
        "8-TRES ESQUINAS (V.ARANDA); >IDA",
        "8-R14 Y CALLE NUEVA; >IDA",
        "8-LA CAPILLA Y SIMONOVICH; >IDA",
        "8-R14 Y SIMONOVICH; >IDA",
        "8-JUMEN; >IDA",
        "8-ESCUELA J. ESPADA; >VUELTA",
        "8-JUMEN; >VUELTA",
        "8-R14 Y SIMONOVICH; >VUELTA",
        "8-LA CAPILLA Y SIMONOVICH; >VUELTA",
        "8-R14 Y CALLE NUEVA; >VUELTA",
        "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
        "8-CRUZ DE PIEDRA; >VUELTA",
        "8-RUSSELL; >VUELTA",
        // Se excluyó MAIPU (MUNICIPALIDAD) por planilla NO en VUELTA
        "8-MAIPU (PERON); >VUELTA",
        "8-ESTACION GUTIERREZ; >VUELTA"
    ],
    "898": [
        "8-ESTACION GUTIERREZ; >IDA",
        "8-MAIPU (PERON); >IDA",
        "8-RUSSELL; >IDA",
        "8-CRUZ DE PIEDRA; >IDA",
        "8-TRES ESQUINAS (V.ARANDA); >IDA",
        "8-R14 Y CALLE NUEVA; >IDA",
        "8-LA CAPILLA Y SIMONOVICH; >VUELTA",
        "8-R14 Y SIMONOVICH; >VUELTA",
        "8-JUMEN; >VUELTA",
        "8-ESCUELA J. ESPADA; >VUELTA",
        "8-JUMEN; >VUELTA",
        "8-R14 Y SIMONOVICH; >VUELTA",
        "8-BRISAS DEL RIO; >VUELTA",
        "8-LA CAPILLA Y SIMONOVICH; >VUELTA",
        "8-R14 Y CALLE NUEVA; >VUELTA",
        "8-TRES ESQUINAS (V.ARANDA); >VUELTA",
        "8-CRUZ DE PIEDRA; >VUELTA",
        "8-RUSSELL; >VUELTA",
        "8-MAIPU (MUNICIPALIDAD); >VUELTA",
        "8-MAIPU (PERON); >VUELTA",
        "8-ESTACION GUTIERREZ; >VUELTA"
    ]
}

},

"G200": {
        
        "recorridos": {
 	    "FUERA-DE-SERVICIO": [
             ],
	    "CONTROL-CORRALITOS": [
            ],
            "QUEDE-TERMINAL": [
            ],
	    "CONTROL-RODEO": [
            ],
	    
	   "1208": [
                "2-SALIDA TERMINAL; >IDA",
                "2-BELTRAN Y SAN MARTIN; >IDA",
                "2-25 DE MAYO Y LAS HERAS; >IDA",
                "2-INGRESO UNC; >IDA",
                "2-SALIDA UNC; >IDA",
                "2-Bº LA FAVORITA; >VUELTA",
                "2-SALIDA UNC; >VUELTA",
                "2-INGRESO UNC; >VUELTA",
                "2-B.SUR MER Y JUAN B. JUSTO; >VUELTA",
                "2-25 DE MAYO Y LAS HERAS; >VUELTA",
                "2-SAN MARTIN Y GODOY CRUZ; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
           
            "1293": [
                "2-SALIDA TERMINAL; >IDA",
                "2-ESC. EVA PERON; >VUELTA",
                "2-ROTONDA ORZALI; >VUELTA",
                "2-SALA 1º AUXILIOS; >VUELTA",
                "2-Bª LA FAVORITA; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "1297": [
                "2-SALIDA TERMINAL; >IDA",
                "2-ESC. VIDELA CORREA; >VUELTA",
                "2-B. SUR MER (LOCALES); >VUELTA",
                "2-Bº OLIVARES; >VUELTA",
                "2-Bª LA FAVORITA; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "200": [
                "2-CONTROL RODEO; >IDA",
                "2-ARCO; >IDA",
                "2-TIRASSO Y ACC; >IDA",
                "2-LIBERTAD; >IDA",
                "2-SARMIENTO; >IDA",
                "2-H.CENTRAL; >IDA",
                "2-BOULOGNE SUR MER; >IDA",
                "2-Bº LA FAVORITA; >VUELTA",
                "2-ROTONDA ORZALI; >VUELTA",
                "2-BOULOGNE SUR MER; >VUELTA",
                "2-PERU Y SARMIENTO; >VUELTA",
                "2-ALEM Y COSTANERA; >VUELTA",
                "2-SARMIENTO; >VUELTA",
                "2-LIBERTAD; >VUELTA",
                "2-TIRASSO Y ACC; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "201": [
                "2-CONTROL RODEO; >IDA",
                "2-Bº ESCORIHUELA; >IDA",
                "2-TIRASSO Y ACC; >IDA",
                "2-LIBERTAD; >IDA",
                "2-SARMIENTO; >IDA",
                "2-H.CENTRAL; >IDA",
                "2-BOULOGNE SUR MER; >VUELTA",
                "2-Bª LA FAVORITA; >VUELTA",
                "2-ROTONDA ORZALI; >VUELTA",
                "2-BOULOGNE SUR MER; >VUELTA",
                "2-PERU Y SARMIENTO; >VUELTA",
                "2-ALEM Y COSTANERA; >VUELTA",
                "2-SARMIENTO; >VUELTA",
                "2-LIBERTAD; >VUELTA",
                "2-TIRASSO Y ACC; >VUELTA",
                "2-Bº ESCORIHUELA; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "202": [
                "2-CONTROL RODEO; >IDA",
                "2-ARCO; >IDA",
                "2-HUENTATA Y BERMEJO; >IDA",
                "2-TIRASSO Y LOS GUINDOS; >IDA",
                "2-URQUIZA Y ESPAÑA; >IDA",
                "2-P.CASTILLO Y AVELLANEDA; >IDA",
                "2-MITRE Y G. CRUZ; >IDA",
                "2-H.CENTRAL; >IDA",
                "2-MONTEVIDEO Y 25 DE MAYO; >VUELTA",
                "2-TERMINAL; >VUELTA",
                "2-MITRE Y G. CRUZ; >VUELTA",
                "2-P.CASTILLO Y AVELLANEDA; >VUELTA",
                "2-P.CASTILLO Y URQUIZA; >VUELTA",
                "2-TIRASSO Y LOS GUINDOS; >VUELTA",
                "2-HUENTATA Y BERMEJO; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "203": [
                "2-CONTROL RODEO; >IDA",
                "2-ARCO; >IDA",
                "2-TIRASSO Y GODOY CRUZ; >IDA",
                "2-B° MUNICIPAL; >IDA",
                "2-B° SUYAI; >IDA",
                "2-TIRASSO Y GODOY CRUZ; >IDA",
                "2-SARMIENTO Y GODOY CRUZ; >IDA",
                "2-OBRIEN Y COSTANERA; >IDA",
                "2-MONTEVIDEO Y 25 DE MAYO; >VUELTA",
                "2-TERMINAL; >VUELTA",
                "2-SARMIENTO Y GODOY CRUZ; >VUELTA",
                "2-TIRASSO Y GODOY CRUZ; >VUELTA",
                "2-B° SUYAI; >VUELTA",
                "2-B° MUNICIPAL; >VUELTA",
                "2-TIRASSO Y GODOY CRUZ; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "204": [
                "2-CONTROL RODEO; >IDA",
                "2-Bº ESCORIHUELA; >IDA",
                "2-TIRASSO Y ACC; >IDA",
                "2-TIRASSO Y TOMAS DE AQUINO; >IDA",
                "2-B° PRADERAS DEL SOL; >IDA",
                "2-B° PARAGUAY; >IDA",
                "2-TIRASSO Y GODOY CRUZ; >IDA",
                "2-SARMIENTO Y GODOY CRUZ; >IDA",
                "2-OBRIEN Y COSTANERA; >IDA",
                "2-MONTEVIDEO Y 25 DE MAYO; >VUELTA",
                "2-TERMINAL; >VUELTA",
                "2-SARMIENTO Y GODOY CRUZ; >VUELTA",
                "2-TIRASSO Y GODOY CRUZ; >VUELTA",
                "2-B° PRADERAS DEL SOL; >VUELTA",
                "2-Bº ESCORIHUELA; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "205": [
                "2-SALIDA TERMINAL; >IDA",
                "2-BELTRAN Y SAN MARTIN; >IDA",
                "2-25 DE MAYO Y LAS HERAS; >IDA",
                "2-INGRESO UNC; >IDA",
                "2-Bº LA FAVORITA; >VUELTA",
                "2-INGRESO UNC; >VUELTA",
                "2-B.SUR MER Y JUAN B. JUSTO; >VUELTA",
                "2-25 DE MAYO Y LAS HERAS; >VUELTA",
                "2-SAN MARTIN Y GODOY CRUZ; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "206": [
                "2-SALIDA TERMINAL; >IDA",
                "2-H.CENTRAL; >IDA",
                "2-PATRICIAS Y MONTEVIDEO; >IDA",
                "2-SARMIENTO Y PERU; >IDA",
                "2-B. SUR MER (LOCALES); >IDA",
                "2-ROTONDA ORZALI.; >IDA",
                "2-Bª LA FAVORITA; >IDA",
                "2-ESC. CLARET; >IDA",
                "2-LOS PUESTOS; >VUELTA",
                "2-ESC. CLARET; >VUELTA",
                "2-B. SUR MER (LOCALES); >VUELTA",
                "2-SARMIENTO Y 25 DE MAYO; >VUELTA",
                "2-PEDRO MOLINA Y SAN MARTIN; >VUELTA",
                "2-H.CENTRAL; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "207": [
                "2-SALIDA TERMINAL; >IDA",
                "2-MONTEVIDEO Y CHILE; >IDA",
                "2-B. SUR MER (LOCALES); >IDA",
                "2-CLUB REGATTAS; >IDA",
                "2-ROTONDA ORZALI; >IDA",
                "2-HOSPITAL LAGOMAGGIORE; >IDA",
                "2-USPALLATA Y PADRE LLORENS; >IDA",
                "2-ROTONDA ORZALI.; >IDA",
                "2-Bº LA FAVORITA; >VUELTA",
                "2-HOSPITAL LAGOMAGGIORE; >VUELTA",
                "2-CLUB REGATTAS; >VUELTA",
                "2-B. SUR MER (LOCALES); >VUELTA",
                "2-PATRICIAS Y MONTEVIDEO; >VUELTA",
                "2-PEDRO MOLINA Y SAN MARTIN; >VUELTA",
                "2-H.CENTRAL; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "208": [
                "2-SALIDA TERMINAL; >IDA",
                "2-BELTRAN Y SAN MARTIN; >IDA",
                "2-25 DE MAYO Y LAS HERAS; >IDA",
                "2-INGRESO UNC; >IDA",
                "2-SALIDA UNC; >IDA",
                "2-Bº LA FAVORITA; >IDA",
                "2-SALIDA UNC; >VUELTA",
                "2-INGRESO UNC; >VUELTA",
                "2-B.SUR MER Y JUAN B. JUSTO; >VUELTA",
                "2-25 DE MAYO Y LAS HERAS; >VUELTA",
                "2-SAN MARTIN Y GODOY CRUZ; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "221": [
                "2-SALIDA TERMINAL; >IDA",
                "2-COLON Y PATRICIAS; >IDA",
                "2-RIOJA Y RONDEAU; >IDA",
                "2-SARMIENTO Y ACCESO ESTE; >IDA",
                "2-ARENALES Y ACCESO ESTE; >IDA",
                "2-TAPON MOYANO; >IDA",
                "2-PONCE Y BANDERA; >IDA",
                "2-DURAND; >IDA",
                "2-PUENTE DE HIERRO; >IDA",
                "2-VIOLETAS; >IDA",
                "2-EL VERGEL; >IDA",
                "2-VIOLETAS; >VUELTA",
                "2-PUENTE DE HIERRO; >VUELTA",
                "2-DURAND; >VUELTA",
                "2-PONCE Y BANDERA; >VUELTA",
                "2-TAPON MOYANO; >VUELTA",
                "2-ARENALES Y ACCESO ESTE; >VUELTA",
                "2-SARMIENTO Y ACCESO ESTE; >VUELTA",
                "2-COLON Y PATRICIAS; >VUELTA",
                "2-RIOJA Y RONDEAU; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "230": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-DURAND; >IDA",
                "2-MILAGROS Y GODOY CRUZ; >IDA",
                "2-ARCO; >IDA",
                "2-TIRASSO Y ACC; >IDA",
                "2-ARENALES; >IDA",
                "2-SARMIENTO Y ACCESO ESTE; >IDA",
                "2-H.CENTRAL; >IDA",
                "2-COLON Y PATRICIAS; >VUELTA",
                "2-RIOJA Y RONDEAU; >VUELTA",
                "2-SARMIENTO Y ACCESO ESTE; >VUELTA",
                "2-ARENALES; >VUELTA",
                "2-TIRASSO Y ACC; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-MILAGROS Y GODOY CRUZ; >VUELTA",
                "2-DURAND; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA"
            ],
            "232": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-SEVERO Y R20; >IDA",
                "2-MILAGROS Y GODOY CRUZ; >IDA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >IDA",
                "2-ARCO; >IDA",
                "2-TIRASSO Y ACC; >IDA",
                "2-ESPAÑA Y LIBERTAD; >VUELTA",
                "2-ARENALES Y BANDERA; >VUELTA",
                "2-TIRASSO Y ACC; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "2-SEVERO Y R20; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA"
            ],
            "233": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-DURAND; >IDA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >IDA",
                "2-ARCO; >IDA",
                "2-TIRASSO Y ACC; >IDA",
                "2-ARENALES; >IDA",
                "2-SARMIENTO; >IDA",
                "2-H.CENTRAL; >VUELTA",
                "2-TERMINAL; >VUELTA",
                "2-SARMIENTO; >VUELTA",
                "2-ARENALES; >VUELTA",
                "2-TIRASSO Y ACC; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "2-DURAND; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA"
            ],
            "234": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-SAN JUAN Y SEVERO C.; >IDA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >IDA",
                "2-ARCO; >IDA",
                "2-TIRASSO Y GODOY CRUZ; >IDA",
                "2-ARENALES Y G.CRUZ; >IDA",
                "2-SARMIENTO Y GODOY CRUZ; >IDA",
                "2-H.CENTRAL; >IDA",
                "2-TERMINAL; >VUELTA",
                "2-SARMIENTO Y GODOY CRUZ; >VUELTA",
                "2-ARENALES Y G.CRUZ; >VUELTA",
                "2-TIRASSO Y GODOY CRUZ; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "2-SAN JUAN Y SEVERO C.; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA"
            ],
            "235": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-SEVERO Y FERRARI; >IDA",
                "2-FERRARI Y BUENOS VECINOS; >IDA",
                "2-ESC. LUGONES; >IDA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >IDA",
                "2-ARCO; >IDA",
                "2-TIRASSO Y GODOY CRUZ; >IDA",
                "2-ARENALES Y G.CRUZ; >IDA",
                "2-SARMIENTO Y GODOY CRUZ; >IDA",
                "2-H.CENTRAL; >IDA",
                "2-RIOJA Y RONDEAU; >IDA",
                "2-TERMINAL; >VUELTA",
                "2-SARMIENTO Y GODOY CRUZ; >VUELTA",
                "2-ARENALES Y G.CRUZ; >VUELTA",
                "2-TIRASSO Y GODOY CRUZ; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "2-ESC. LUGONES; >VUELTA",
                "2-FERRARI Y BUENOS VECINOS; >VUELTA",
                "2-SEVERO Y FERRARI; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA"
            ],
            "236": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-SEVERO Y FERRARI; >VUELTA",
                "2-FERRARI Y BUENOS VECINOS; >VUELTA",
                "2-SANCHEZ Y BUENOS AIRES; >VUELTA",
                "2-ESC. LUGONES; >VUELTA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "2-KM 14; >VUELTA",
                "2-PONCE Y BANDERA; >VUELTA",
                "2-ARCO DE RODEO; >VUELTA",
                "2-KM 14; >VUELTA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "2-ESC. LUGONES; >VUELTA",
                "2-SANCHEZ Y BUENOS AIRES; >VUELTA",
                "2-FERRARI Y BUENOS VECINOS; >VUELTA",
                "2-SEVERO Y FERRARI; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA"
            ],
            "240": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-DURAND; >VUELTA",
                "2-R20 Y RECONQUISTA; >VUELTA",
                "2-V.HUGO Y H.PRIMO; >VUELTA",
                "2-PRIMAVERA; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-TIRASSO Y GODOY CRUZ; >VUELTA",
                "2-URQUIZA Y G.CRUZ; >VUELTA",
                "2-BANDERA Y LIBERTAD; >VUELTA",
                "2-BANDERA Y BOLIVIA; >VUELTA",
                "2-SARMIENTO; >VUELTA",
                "2-ARENALES; >VUELTA",
                "2-MUNICIPALIDAD; >VUELTA",
                "2-URQUIZA Y G.CRUZ; >VUELTA",
                "2-TIRASSO Y GODOY CRUZ; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-PRIMAVERA; >VUELTA",
                "2-V.HUGO Y H.PRIMO; >VUELTA",
                "2-R20 Y RECONQUISTA; >VUELTA",
                "2-DURAND; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA"
            ],
            "241": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-DURAND; >IDA",
                "2-R20 Y SERPA; >IDA",
                "2-PRIMAVERA; >IDA",
                "2-DIABLILLO Y ARGUMEDO; >IDA",
                "2-ROTONDA SALCEDO; >IDA",
                "2-MILAGROS Y GODOY CRUZ; >IDA",
                "2-ARCO; >IDA",
                "2-TIRASSO Y GODOY CRUZ; >IDA",
                "2-SARMIENTO Y GODOY CRUZ; >IDA",
                "2-H.CENTRAL; >VUELTA",
                "2-TERMINAL; >VUELTA",
                "2-SARMIENTO Y GODOY CRUZ; >VUELTA",
                "2-TIRASSO Y GODOY CRUZ; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-MILAGROS Y GODOY CRUZ; >VUELTA",
                "2-ROTONDA SALCEDO; >VUELTA",
                "2-PRIMAVERA; >VUELTA",
                "2-R20 Y SERPA; >VUELTA",
                "2-DURAND; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA"
            ],
            "242": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-DURAND; >IDA",
                "2-BUENOS AIRES Y SAAVEDRA; >IDA",
                "2-R20 Y SERPA; >IDA",
                "2-PRIMAVERA; >IDA",
                "2-DIABLILLO Y PALADINI; >IDA",
                "2-SEVERO Y ARGUMEDO; >IDA",
                "2-MILAGROS Y BANDERA; >IDA",
                "2-ARCO; >IDA",
                "2-TIRASSO Y GODOY CRUZ; >IDA",
                "2-SARMIENTO Y GODOY CRUZ; >IDA",
                "2-H.CENTRAL; >IDA",
                "2-TERMINAL; >VUELTA",
                "2-SARMIENTO Y GODOY CRUZ; >VUELTA",
                "2-TIRASSO Y GODOY CRUZ; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-MILAGROS Y BANDERA; >VUELTA",
                "2-SEVERO Y ARGUMEDO; >VUELTA",
                "2-PRIMAVERA; >VUELTA",
                "2-R20 Y SERPA; >VUELTA",
                "2-BUENOS AIRES Y SAAVEDRA; >VUELTA",
                "2-DURAND; >VUELTA"
            ],
            "250": [
                "2-CONTROL RODEO; >IDA",
                "2-PASCUAL LAURIENTE; >IDA",
                "2-SEVERO Y R20; >IDA",
                "2-2 DE MAYO; >IDA",
                "2-SERPA Y MITRE; >IDA",
                "2-R20 Y LOS ALAMOS; >IDA",
                "2-ROMA Y DON BOSCO; >VUELTA",
                "2-ROMA Y SAN JOSE; >VUELTA",
                "2-LOS BAÑOS Y LAT. ACCCESO ESTE; >VUELTA",
                "2-HTAL. METRAUX; >VUELTA",
                "2-R50 Y LOS BAÑOS; >VUELTA",
                "2-PASCUAL LAURIENTE; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "251": [
                "2-CONTROL RODEO; >IDA",
                "2-PASCUAL LAURIENTE; >IDA",
                "2-R50 Y LOS BAÑOS; >IDA",
                "2-HTAL. METRAUX; >IDA",
                "2-LOS BAÑOS Y LAT. ACCCESO ESTE; >IDA",
                "2-ROMA Y SAN JOSE; >IDA",
                "2-ROMA Y DON BOSCO; >VUELTA",
                "2-R20 Y LOS ALAMOS; >VUELTA",
                "2-SERPA Y MITRE; >VUELTA",
                "2-2 DE MAYO; >VUELTA",
                "2-SEVERO Y R20; >VUELTA",
                "2-PASCUAL LAURIENTE; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "252": [
                "2-SALIDA TERMINAL; >IDA",
                "2-SALTA Y GARIBALDI; >IDA",
                "2-SARMIENTO; >IDA",
                "2-LIBERTAD; >IDA",
                "2-URQUIZA; >IDA",
                "2-TIRASSO Y ACC; >IDA",
                "2-ARCO; >IDA",
                "2-KM 8; >IDA",
                "2-R50 Y DON BOSCO; >IDA",
                "2-R20 Y DON BOSCO; >VUELTA",
                "2-R50 Y DON BOSCO; >VUELTA",
                "2-KM 8; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-TIRASSO Y ACC; >VUELTA",
                "2-URQUIZA; >VUELTA",
                "2-LIBERTAD; >VUELTA",
                "2-SARMIENTO; >VUELTA",
                "2-H.CENTRAL; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "260": [
                "2-SALIDA TERMINAL; >IDA",
                "2-CATAMARCA Y RIOJA; >IDA",
                "2-SARMIENTO Y ACCESO ESTE; >IDA",
                "2-ARENALES Y ACCESO ESTE; >IDA",
                "2-TIRASSO Y ACC; >IDA",
                "2-ARCO; >IDA",
                "2-KM 11; >IDA",
                "2-PRIMAVERA; >IDA",
                "2-Bº 25 DE MAYO; >IDA",
                "2-R50 Y DON BOSCO; >IDA",
                "2-HTAL. METRAUX; >VUELTA",
                "2-R50 Y LOS BAÑOS; >VUELTA",
                "2-R50 Y SERPA; >VUELTA",
                "2-R20 Y SERPA; >VUELTA",
                "2-PRIMAVERA; >VUELTA",
                "2-KM 8; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-TIRASSO Y ACC; >VUELTA",
                "2-ARENALES Y ACCESO ESTE; >VUELTA",
                "2-SARMIENTO Y ACCESO ESTE; >VUELTA",
                "2-H.CENTRAL; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "261": [
                "2-SALIDA TERMINAL; >IDA",
                "2-CATAMARCA Y RIOJA; >IDA",
                "2-SARMIENTO Y ACCESO ESTE; >IDA",
                "2-ARENALES Y ACCESO ESTE; >IDA",
                "2-TIRASSO Y ACC; >IDA",
                "2-ARCO; >IDA",
                "2-KM 11; >IDA",
                "2-R50 Y DON BOSCO; >IDA",
                "2-R20 Y DON BOSCO; >VUELTA",
                "2-ROMA Y DON BOSCO; >VUELTA",
                "2-ROMA Y SAN JOSE; >VUELTA",
                "2-R50 Y LOS BAÑOS; >VUELTA",
                "2-KM 11; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-TIRASSO Y ACC; >VUELTA",
                "2-ARENALES Y ACCESO ESTE; >VUELTA",
                "2-SARMIENTO Y ACCESO ESTE; >VUELTA",
                "2-H.CENTRAL; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "270": [
                "2-CONTROL RODEO; >IDA",
                "2-PASCUAL LAURIENTE; >IDA",
                "2-R50 Y LOS ALAMOS; >IDA",
                "2-R20 Y LOS ALAMOS; >IDA",
                "2-R20 Y R33; >IDA",
                "2-ESCUELA TITARELLI; >VUELTA",
                "2-R50 Y LAS MARGARITAS; >VUELTA",
                "2-R50 Y LOS BAÑOS; >VUELTA",
                "2-KM 8; >VUELTA",
                "2-PASCUAL LAURIENTE; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "271": [
                "2-CONTROL RODEO; >IDA",
                "2-PASCUAL LAURIENTE; >IDA",
                "2-R50 Y LOS BAÑOS; >IDA",
                "2-R50 Y LAS MARGARITAS; >IDA",
                "2-ESCUELA TITARELLI; >IDA",
                "2-R20 Y R33; >IDA",
                "2-R20 Y LOS ALAMOS; >VUELTA",
                "2-R50 Y LOS ALAMOS; >VUELTA",
                "2-R50 Y LOS BAÑOS; >VUELTA",
                "2-PASCUAL LAURIENTE; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "272": [
                "2-CONTROL RODEO; >IDA",
                "2-ESC. ARGUMEDO; >IDA",
                "2-ESC. SILVANO RODRIGUEZ; >IDA",
                "2-BUENOS AIRES Y SAAVEDRA; >VUELTA",
                "2-COL. SAGRADA FAMILIA; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "273": [
                "2-CONTROL RODEO; >IDA",
                "2-ARCO; >IDA",
                "2-ESC. ARGUMEDO; >IDA",
                "2-PUENTE DE HIERRO; >IDA",
                "2-ESC. MAESTROS MENDOCINOS; >IDA",
                "2-PUENTE DE HIERRO; >VUELTA",
                "2-SEVERO Y R20; >VUELTA",
                "2-ROTONDA SALCEDO; >VUELTA",
                "2-SEVERO Y ARGUMEDO; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "274": [
                "2-CONTROL RODEO; >IDA",
                "2-ESC. ARGUMEDO; >IDA",
                "2-ESC. LUGONES; >VUELTA",
                "2-FERRARI Y TABANERA; >VUELTA",
                "2-PUENTE DE HIERRO; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "275": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-B° LAS CHACRAS; >IDA",
                "2-SEVERO Y SAENZ PEÑA; >IDA",
                "2-ESC. CORSINO; >VUELTA",
                "2-ESC. PESTALOZZI; >VUELTA",
                "2-B° LAS CHACRAS; >VUELTA",
                "2-S.CASTILLO Y GRENON; >VUELTA",
                "2-EL MOLINO; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA"
            ],
            "276": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-B° LAS CHACRAS; >IDA",
                "2-SEVERO Y SAENZ PEÑA; >IDA",
                "2-ESC. CORSINO; >IDA",
                "2-ESC. PESTALOZZI; >VUELTA",
                "2-SEVERO Y SAENZ PEÑA; >VUELTA",
                "2-B° LAS CHACRAS; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA"
            ],
            "277": [
                "2-CONTROL RODEO; >IDA",
                "2-KM 8; >IDA",
                "2-ACC. ESTE Y R50; >IDA",
                "2-NECOCHEA Y R50; >IDA",
                "2-ESC. PEDRO VARELA; >IDA",
                "2-NECOCHEA Y R50; >IDA",
                "2-PZA Bº 25 DE MAYO; >IDA",
                "2-Bª25 DE JUNIO; >IDA",
                "2-PZA Bº 25 DE MAYO; >VUELTA",
                "2-NECOCHEA Y R50; >VUELTA",
                "2-ESC. PEDRO VARELA; >VUELTA",
                "2-ACC. ESTE Y R50; >VUELTA",
                "2-KM 8; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "278": [
                "2-CONTROL RODEO; >IDA",
                "2-KM 8; >IDA",
                "2-ACC. ESTE Y R50; >IDA",
                "2-NECOCHEA Y R50; >IDA",
                "2-TROPERO Y NECOCHEA; >VUELTA",
                "2-PZA Bº 25 DE MAYO; >VUELTA",
                "2-NECOCHEA Y R50; >VUELTA",
                "2-ESC. PEDRO VARELA; >VUELTA",
                "2-ACC. ESTE Y R50; >VUELTA",
                "2-KM 8; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "279": [
                "2-CONTROL RODEO; >IDA",
                "2-KM 8; >IDA",
                "2-ACC. ESTE Y R50; >IDA",
                "2-ESC. PEDRO VARELA; >IDA",
                "2-NECOCHEA Y R50; >IDA",
                "2-PZA Bº 25 DE MAYO; >IDA",
                "2-Bª25 DE JUNIO; >VUELTA",
                "2-NECOCHEA Y R50; >VUELTA",
                "2-ACC. ESTE Y R50; >VUELTA",
                "2-KM 8; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "280": [
                "2-CONTROL RODEO; >IDA",
                "2-SERPA Y ACCESO ESTE; >IDA",
                "2-ESC. REMEDIOS ESCALADA; >IDA",
                "2-SERPA Y ACCESO ESTE; >VUELTA",
                "2-ESC. PESCARA; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "281": [
                "2-CONTROL RODEO; >IDA",
                "2-ARCO; >IDA",
                "2-KM 8; >IDA",
                "2-ESC. ISIDRO MAZA; >IDA",
                "2-R50 Y DON BOSCO; >IDA",
                "2-R20 Y DON BOSCO; >VUELTA",
                "2-ESC. ISIDRO MAZA; >VUELTA",
                "2-KM 8; >VUELTA",
                "2-RODEO DE LA CRUZ; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "282": [
                "2-CONTROL RODEO; >IDA",
                "2-ESC. ISIDRO MAZA; >IDA",
                "2-R50 Y DON BOSCO; >IDA",
                "2-COL. SAGRADA FAMILIA; >VUELTA",
                "2-ESC. ISIDRO MAZA; >VUELTA",
                "2-COL. SAGRADA FAMILIA; >VUELTA",
                "2-R50 Y LOS BAÑOS; >VUELTA",
                "2-KM 8; >VUELTA",
                "2-ARCO; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "283": [
                "2-CONTROL CORRALITOS; >IDA",
                "2-B° LAS CHACRAS; >IDA",
                "2-SEVERO Y SAENZ PEÑA; >IDA",
                "2-ESC. CORSINO; >VUELTA",
                "2-ESC. PESTALOZZI; >VUELTA",
                "2-SEVERO Y SAENZ PEÑA; >VUELTA",
                "2-B° LAS CHACRAS; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA"
            ],
            "284": [
                "2-CONTROL RODEO; >IDA",
                "2-R50 Y DON BOSCO; >IDA",
                "2-ROMA Y DON BOSCO; >IDA",
                "2-DON BOSCO Y SAN MARTIN; >IDA",
                "2-R20 Y DON BOSCO; >IDA",
                "2-BUENOS AIRES Y SAAVEDRA; >IDA",
                "2-R20 Y SERPA; >IDA",
                "2-R50 Y SERPA; >VUELTA",
                "2-R20 Y SERPA; >VUELTA",
                "2-BUENOS AIRES Y SAAVEDRA; >VUELTA",
                "2-R20 Y DON BOSCO; >VUELTA",
                "2-DON BOSCO Y SAN MARTIN; >VUELTA",
                "2-ROMA Y DON BOSCO; >VUELTA",
                "2-R50 Y DON BOSCO; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "285": [
                "2-CONTROL RODEO; >IDA",
                "2-ESC. MAESTROS MENDOCINOS; >IDA",
                "2-PUENTE DE HIERRO; >VUELTA",
                "2-ESC. ARGUMEDO; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "286": [
                "2-CONTROL RODEO; >IDA",
                "2-FERRARI Y MILAGROS; >IDA",
                "2-ESC. LUGONES; >IDA",
                "2-ESC. FELIX BOGADO; >IDA",
                "2-ESC. ARGUMEDO; >VUELTA",
                "2-Bº MALVINAS; >VUELTA",
                "2-ESC. MAESTROS MENDOCINOS; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "287": [
                "2-CONTROL RODEO; >IDA",
                "2-ARCO; >IDA",
                "2-FERRARI Y MILAGROS; >IDA",
                "2-PUENTE DE HIERRO; >IDA",
                "2-ESC. MAESTROS MENDOCINOS; >IDA",
                "2-PUENTE DE HIERRO; >VUELTA",
                "2-FERRARI Y MILAGROS; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "288": [
                "2-CONTROL RODEO; >IDA",
                "2-ESC. ARGUMEDO; >IDA",
                "2-PUENTE DE HIERRO; >IDA",
                "2-Bº SAN VICENTE; >VUELTA",
                "2-SEVERO Y R20; >VUELTA",
                "2-ESC. ARGUMEDO; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "289": [
                "2-CONTROL RODEO; >IDA",
                "2-ESC. ARGUMEDO; >IDA",
                "2-PRIMAVERA; >IDA",
                "2-H.PRIMO Y OLASCOAGA; >IDA",
                "2-SEVERO Y R20; >VUELTA",
                "2-ROTONDA SALCEDO; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "290": [
                "2-CONTROL RODEO; >IDA",
                "2-ESC. ARGUMEDO; >IDA",
                "2-ESC. SILVANO RODRIGUEZ; >IDA",
                "2-BUENOS AIRES Y SAAVEDRA; >VUELTA",
                "2-ESC. SILVANO RODRIGUEZ; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "291": [
                "2-CONTROL RODEO; >IDA",
                "2-ESC. ARGUMEDO; >IDA",
                "2-ESC. SILVANO RODRIGUEZ; >VUELTA",
                "2-COL. SAGRADA FAMILIA; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "292": [
                "2-SALIDA TERMINAL; >IDA",
                "2-ESC SARMIENTO; >VUELTA",
                "2-B. SUR MER (LOCALES); >VUELTA",
                "2-ROTONDA ORZALI.; >VUELTA",
                "2-Bª LA FAVORITA; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "293": [
                "2-SALIDA TERMINAL; >IDA",
                "2-Bª LA FAVORITA; >VUELTA",
                "2-SALA 1º AUXILIOS; >VUELTA",
                "2-ROTONDA ORZALI; >VUELTA",
                "2-ESC. EVA PERON; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "294": [
                "2-CONTROL RODEO; >IDA",
                "2-SERPA Y ACCESO ESTE; >IDA",
                "2-ESC. PESCARA; >IDA",
                "2-ESC. REMEDIOS ESCALADA; >VUELTA",
                "2-SERPA Y ACCESO ESTE; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "295": [
                "2-CONTROL RODEO; >IDA",
                "2-SERPA Y ACCESO ESTE; >IDA",
                "2-ESC. PESCARA; >IDA",
                "2-ESC. REMEDIOS ESCALADA; >VUELTA",
                "2-SERPA Y ACCESO ESTE; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "296": [
                "2-CONTROL RODEO; >IDA",
                "2-SERPA Y ACCESO ESTE; >IDA",
                "2-ESC. REMEDIOS ESCALADA; >VUELTA",
                "2-SERPA Y ACCESO ESTE; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ],
            "297": [
                "2-SALIDA TERMINAL; >IDA",
                "2-Bª LA FAVORITA; >IDA",
                "2-Bº OLIVARES; >VUELTA",
                "2-ESC. VIDELA CORREA; >VUELTA",
                "2-SALIDA TERMINAL; >VUELTA"
            ],
            "298": [
                "2-CONTROL RODEO; >IDA",
                "2-ESC. ARGUMEDO; >IDA",
                "2-PONCE Y BANDERA; >IDA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >IDA",
                "2-ESC. LUGONES; >IDA",
                "2-SANCHEZ Y BUENOS AIRES; >IDA",
                "2-FERRARI Y BUENOS VECINOS; >IDA",
                "2-SEVERO Y FERRARI; >IDA",
                "2-CONTROL CORRALITOS; >VUELTA",
                "2-CONTROL CORRALITOS; >VUELTA",
                "2-SEVERO Y FERRARI; >VUELTA",
                "2-FERRARI Y BUENOS VECINOS; >VUELTA",
                "2-SANCHEZ Y BUENOS AIRES; >VUELTA",
                "2-ESC. LUGONES; >VUELTA",
                "2-GODOY CRUZ Y BUENOS VECINOS; >VUELTA",
                "2-PONCE Y BANDERA; >VUELTA",
                "2-CONTROL RODEO; >VUELTA"
            ]
        
        }
    }
};